### ISSUE TITLE
Need Help in using custom dataset(Important)

### ISSUE THREAD

**Issue by minakshimathpal** [rom1504/clip-retrieval#108]
@rom1504 Hi there. I have a fashion image dataset which has the images itself not the urls. Is there any way to use that dataset in "CLIP for Image Retrieval,ipynb"....Please help

**Comment by rom1504** [comment]
yes start directly from clip inference and use the files input format

**Comment by minakshimathpal** [comment]
@rom1504 This is the query i am writing
![image](https://user-images.githubusercontent.com/61991627/154579266-0887a6eb-4719-48e9-af49-d79e196406ef.png)

**Comment by minakshimathpal** [comment]
Contents of the folder which i am trying to read
![image](https://user-images.githubusercontent.com/61991627/154579547-7a774332-cd23-4685-9126-0774d435a3a7.png)

**Comment by rom1504** [comment]
Img2dataset purpose is to download images. If you already have image files you don't need to use it at all

**Comment by minakshimathpal** [comment]
https://the-eye.eu/public/AI/cah/laion400m-met-release/laion400m-meta/ 
this link is not responding. Used kaggle to download first part of the dataset in .parquet format

**Comment by rom1504** [comment]
yes colab is not a good environment for downloading. To use img2dataset efficiently you need high bandwidth and several good cpu cores. Colab has none of that
You won't be able to download laion400m here. One parquet file of laion400m is 12.5m samples

**Comment by minakshimathpal** [comment]
@rom1504  thanks a lot for your time

**Comment by minakshimathpal** [comment]
@rom1504  when running clip retrieval inference on my custom data i am getting following error
![image](https://user-images.githubusercontent.com/61991627/154649634-23b9d1b9-32be-4ab2-b97f-8f3459eba4be.png)

**Comment by minakshimathpal** [comment]
yesterday it was runnning...but today not working...using google colab. this is what my image folder looks like
![image](https://user-images.githubusercontent.com/61991627/154649777-da9d3fff-c7c5-4285-a235-b57f3427b6d9.png)

**Comment by minakshimathpal** [comment]
ok...thank you

**Comment by minakshimathpal** [comment]
@rom1504  I am sorry for bugging you repeatedly. I am using CLIP-retreival for fashion domain but the results are not satisfactory. here is an example

![image](https://user-images.githubusercontent.com/61991627/155015455-c0877fc0-935d-4401-bdf2-adca23fe5f5f.png)


when i write black dress, quite a few misclassifications are there. My mentor wants me to improve the results.
How i did i go about using CLIP-retrival
1) calculated embeddings for mscoco  captions 
2) then used my own dataset with just images and calculated embeddings
    why i added ms coco. because when i didn't ,no matter what i give to CLIP-filter it was returning back all the images i used(my own dataset. It has just 50 images as of now)

please guide how can i improve the results else i will be kicked out of the project

**Comment by rom1504** [comment]
What about simply adding more samples to your dataset?

You can use https://www.kaggle.com/paramaggarwal/fashion-product-images-dataset for example

**Comment by minakshimathpal** [comment]
@rom thanks a lot for this dataset

**Comment by rom1504** [comment]
You need to specify the input format

**Comment by rom1504** [comment]
yes just put the files next to the other ones
but what about just merging the 2 datasets initially?

**Comment by minakshimathpal** [comment]
@rom1504  This is a snip of your code from clip_filter.py
![image](https://user-images.githubusercontent.com/61991627/155611474-ee3933fa-01ca-4ae2-99ab-37587c8b2d78.png)
1) is num_results in else block is n_neighbours?
2) how can i use the value of threshold parameter to improve recall

this i get after a query. I think min_d and max_d are minimum and maximum distance of  from from nearest neighbours

![image](https://user-images.githubusercontent.com/61991627/155612488-c941f322-0fa6-446c-b785-37e72dd700e6.png)
