### ISSUE TITLE
typo on read.me? pipe:aws command instructions. Missing "-"

### ISSUE THREAD

**Issue by Rebolforces** [rom1504/clip-retrieval#127]
Read.md is missing the "-" after .tar 

```clip_inference --input_dataset "pipe:aws s3 cp --quiet s3://myfolder/webdataset/{00000..00010}.tar" --output_folder "s3://myfolder/embeddings" --input_format webdataset```

I believe it should be. 
```clip_inference --input_dataset "pipe:aws s3 cp --quiet s3://myfolder/webdataset/{00000..00010}.tar -" --output_folder "s3://myfolder/embeddings" --input_format webdataset```

**Comment by rom1504** [comment]
Yeah you're right
