### ISSUE TITLE
Error reading LAION-5B Index

### ISSUE THREAD

**Issue by hussam789** [rom1504/clip-retrieval#145]
I downloaded LAION-5B Index from [huggingface](https://huggingface.co/datasets/laion/laion5B-index), and ran clip_back script:
`python -m clip_retrieval.clip_back --port 4545 --indices-paths /workspace/clip-retrieval/indices_paths.json --enable_hdf5=False --reorder_metadata_by_ivf_index=True --use_arrow=True --enable_faiss_memory_mapping=True`

and I'm getting this error when reading [1B-nolang.arrow](https://huggingface.co/datasets/laion/laion5B-index/blob/main/metadata/1B-nolang.arrow) file:
`pyarrow.lib.ArrowInvalid: Unexpected empty message in IPC file format`

The other arrow files did not fail

**Comment by rom1504** [comment]
hi @hussam789 can you double check you have the whole file?
it should be 196912210002 bytes

**Comment by hussam789** [comment]
Yes, the size is correct
![image](https://user-images.githubusercontent.com/1441832/169038401-b5f6e11a-b9b2-4b6a-a77a-a16390976c72.png)

**Comment by rom1504** [comment]
That's surprising, if works on my side
Can you try to load it manually through pyarrow to check?

**Comment by hussam789** [comment]
I switched to another machine, and now it works.
Thanks
