### ISSUE TITLE
Something wrong with the metadata

### ISSUE THREAD

**Issue by LearningJack** [rom1504/clip-retrieval#149]
![issue](https://user-images.githubusercontent.com/38984606/169823839-816f20ec-ff59-4069-b655-9fa707ff2545.jpg)
Could you help me? When I run the **clip-retrieval** and the metadata shows containing folders name and files name after run **reorder-embeddings example-key --metadata-folder ./img_emb_test/metadata**, how can I save the metadata without containing folders name?

**Comment by rom1504** [comment]
Looks like you don't have any file called {000000}.tar
Maybe you mean 000000.tar or {000000..000005}.tar ?
