### ISSUE TITLE
ConnectionResetError while running clip-retrieval back

### ISSUE THREAD

**Issue by takusaitoh** [rom1504/clip-retrieval#150]
Hi!

I ran the code below in jupyter notebook.

> from threading import Thread
> 
> def app():
>     !clip-retrieval back --port 1234 --indices-paths indices_paths.json
>  
>  if __name__ == '__main__':
>     t1 = Thread(target = app)
>     a = t1.start()
>     !lt --port 1234

After that, the following error was output.

> /bin/sh: 1: lt: not found
starting boot of clip back
100%|████████████████████████████████████████| 354M/354M [22:15<00:00, 265kiB/s]
Downloading: 100%|██████████████████████████████| 690/690 [00:00<00:00, 514kB/s]
Downloading: 100%|██████████████████████████████| 190/190 [00:00<00:00, 360kB/s]
Downloading: 100%|██████████████████████████████| 115/115 [00:00<00:00, 210kB/s]
Downloading: 100%|█████████████████████████| 1.57M/1.57M [00:00<00:00, 3.90MB/s]
Downloading: 100%|█████████████████████████| 5.63k/5.63k [00:00<00:00, 9.16MB/s]
Downloading: 100%|█████████████████████████████| 572/572 [00:00<00:00, 1.03MB/s]
Downloading: 100%|██████████████████████████████| 122/122 [00:00<00:00, 213kB/s]
Downloading: 100%|██████████████████████████████| 341/341 [00:00<00:00, 614kB/s]
Downloading: 100%|███████████████████████████| 539M/539M [01:13<00:00, 7.31MB/s]
Downloading: 100%|████████████████████████████| 53.0/53.0 [00:00<00:00, 101kB/s]
Downloading: 100%|██████████████████████████████| 112/112 [00:00<00:00, 198kB/s]
Downloading: 100%|██████████████████████████| 1.96M/1.96M [00:05<00:00, 380kB/s]
Downloading: 100%|██████████████████████████████| 371/371 [00:00<00:00, 521kB/s]
Downloading: 100%|████████████████████████████| 996k/996k [00:02<00:00, 343kB/s]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/opt/conda/lib/python3.8/asyncio/base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "/opt/conda/lib/python3.8/asyncio/selector_events.py", line 848, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/fsspec/implementations/http.py", line 383, in _info
    await _file_info(
  File "/opt/conda/lib/python3.8/site-packages/fsspec/implementations/http.py", line 730, in _file_info
    r = await session.get(url, allow_redirects=ar, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/opt/conda/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/opt/conda/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/opt/conda/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/opt/conda/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/opt/conda/lib/python3.8/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host github.com:443 ssl:default [Connection reset by peer]
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
  File "/opt/conda/bin/clip-retrieval", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/clip_retrieval/cli.py", line 16, in main
    fire.Fire(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/clip_retrieval/clip_back.py", line 928, in clip_back
    clip_resources = load_clip_indices(
  File "/opt/conda/lib/python3.8/site-packages/clip_retrieval/clip_back.py", line 901, in load_clip_indices
    clip_resources[name] = load_clip_index(clip_options)
  File "/opt/conda/lib/python3.8/site-packages/clip_retrieval/clip_back.py", line 835, in load_clip_index
    get_aesthetic_embedding(clip_options.clip_model) if clip_options.provide_aesthetic_embeddings else None
  File "/opt/conda/lib/python3.8/site-packages/clip_retrieval/clip_back.py", line 662, in get_aesthetic_embedding
    for _ in pool.imap_unordered(get, range(10)):
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/opt/conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.8/site-packages/clip_retrieval/clip_back.py", line 656, in get
    with fs.open(
  File "/opt/conda/lib/python3.8/site-packages/fsspec/spec.py", line 1009, in open
    f = self._open(
  File "/opt/conda/lib/python3.8/site-packages/fsspec/implementations/http.py", line 343, in _open
    size = size or self.info(path, **kwargs)["size"]
  File "/opt/conda/lib/python3.8/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/opt/conda/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/opt/conda/lib/python3.8/site-packages/fsspec/implementations/http.py", line 396, in _info
    raise FileNotFoundError(url) from exc
FileNotFoundError: https://github.com/LAION-AI/aesthetic-predictor/blob/main/vit_b_32_embeddings/rating6.npy?raw=true

The environment of docker is as follows.

>aiohttp                  3.8.1
aiosignal                1.2.0
albumentations           1.1.0
aniso8601                9.0.1
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
asttokens                2.0.5
async-timeout            4.0.2
attrs                    21.4.0
autofaiss                2.14.3
backcall                 0.2.0
beautifulsoup4           4.11.1
bert-score               0.3.11
bleach                   5.0.0
braceexpand              0.1.7
brotlipy                 0.7.0
cachetools               5.1.0
certifi                  2022.5.18.1
cffi                     1.14.6
chardet                  4.0.0
charset-normalizer       2.0.12
click                    8.1.3
clip-anytorch            2.4.0
clip-retrieval           2.31.1
colorama                 0.4.4
conda                    4.13.0
conda-package-handling   1.7.3
cryptography             3.4.7
cycler                   0.11.0
Cython                   0.29.30
dataclasses              0.6
debugpy                  1.6.0
decorator                5.1.1
defusedxml               0.7.1
docker-pycreds           0.4.0
embedding-reader         1.4.2
entrypoints              0.4
executing                0.8.3
ExifRead-nocycle         3.0.1
faiss-cpu                1.7.2
fastjsonschema           2.15.3
filelock                 3.7.0
fire                     0.4.0
Flask                    2.1.2
Flask-Cors               3.0.10
Flask-RESTful            0.3.9
fonttools                4.33.3
frozenlist               1.3.0
fsspec                   2022.1.0
ftfy                     6.1.1
gitdb                    4.0.9
GitPython                3.1.27
google-api-core          2.8.1
google-auth              2.6.6
google-cloud-core        2.3.0
google-cloud-translate   3.7.3
googleapis-common-protos 1.56.2
grpcio                   1.46.3
grpcio-status            1.46.3
h5py                     3.7.0
huggingface-hub          0.7.0
idna                     2.10
imageio                  2.19.2
img2dataset              1.30.1
importlib-metadata       4.11.4
importlib-resources      5.7.1
ipykernel                6.13.0
ipython                  8.3.0
ipython-genutils         0.2.0
ipywidgets               7.7.0
itsdangerous             2.1.2
jedi                     0.18.1
Jinja2                   3.1.2
joblib                   1.1.0
jsonschema               4.5.1
jupyter                  1.0.0
jupyter-client           7.3.1
jupyter-console          6.4.3
jupyter-core             4.10.0
jupyterlab-pygments      0.2.2
jupyterlab-widgets       1.1.0
kiwisolver               1.4.2
langid                   1.1.6
laserembeddings          1.1.2
MarkupSafe               2.1.1
matplotlib               3.5.2
matplotlib-inline        0.1.3
mistune                  0.8.4
mkl-fft                  1.3.1
mkl-random               1.2.2
mkl-service              2.4.0
mock                     4.0.3
multidict                6.0.2
nbclient                 0.6.3
nbconvert                6.5.0
nbformat                 5.4.0
nest-asyncio             1.5.5
networkx                 2.8.2
nltk                     3.7
notebook                 6.4.11
numpy                    1.22.3
open-clip-torch          1.2.1
opencv-python            4.5.5.64
opencv-python-headless   4.5.5.64
packaging                21.3
pandas                   1.4.2
pandocfilters            1.5.0
parso                    0.8.3
pathtools                0.1.2
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.0.1
pip                      21.1.3
portalocker              2.4.0
prometheus-client        0.14.1
promise                  2.3
prompt-toolkit           3.0.29
proto-plus               1.20.5
protobuf                 3.20.1
psutil                   5.9.1
ptyprocess               0.7.0
pure-eval                0.2.2
py-rouge                 1.1
py4j                     0.10.9.3
pyarrow                  7.0.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycosat                  0.6.3
pycparser                2.20
Pygments                 2.12.0
pyOpenSSL                20.0.1
pyparsing                3.0.9
pyrsistent               0.18.1
PySocks                  1.7.1
pyspark                  3.2.1
python-dateutil          2.8.2
pytz                     2022.1
PyWavelets               1.3.0
PyYAML                   6.0
pyzmq                    23.0.0
qtconsole                5.3.0
QtPy                     2.1.0
qudida                   0.0.4
regex                    2022.4.24
requests                 2.27.1
rsa                      4.8
ruamel-yaml-conda        0.15.100
ruamel.yaml              0.17.21
ruamel.yaml.clib         0.2.6
sacrebleu                2.1.0
sacremoses               0.0.35
scikit-image             0.19.2
scikit-learn             1.1.1
scipy                    1.8.1
Send2Trash               1.8.0
sentence-transformers    2.2.0
sentencepiece            0.1.96
sentry-sdk               1.5.12
setproctitle             1.2.3
setuptools               52.0.0.post20210125
shortuuid                1.0.9
six                      1.16.0
smmap                    5.0.0
SoundFile                0.10.3.post1
soupsieve                2.3.2.post1
stack-data               0.2.0
stanfordcorenlp          3.9.1.1
subword-nmt              0.3.8
tabulate                 0.8.9
termcolor                1.1.0
terminado                0.15.0
threadpoolctl            3.1.0
tifffile                 2022.5.4
timm                     0.5.4
tinycss2                 1.1.1
tokenizers               0.12.1
torch                    1.10.1
torchaudio               0.10.1
torchvision              0.11.2
tornado                  6.1
tqdm                     4.62.3
traitlets                5.2.1.post0
transformers             4.19.2
transliterate            1.10.2
typing-extensions        4.1.1
urllib3                  1.26.6
vizseq                   0.1.15
wandb                    0.12.17
wcwidth                  0.2.5
webdataset               0.1.103
webencodings             0.5.1
Werkzeug                 2.1.2
wheel                    0.36.2
widgetsnbextension       3.6.0
yarl                     1.7.2
zipp                     3.8.0

If you have any idea on the cause of this problem, please let me know.

**Comment by rom1504** [comment]
The error is aiohttp.client_exceptions.ClientConnectorError: Cannot connect
to host github.com:443 ssl:default [Connection reset by peer]

Is GitHub available where you're running this ?

**Comment by takusaitoh** [comment]
Thank you so much for your response.

I confirmed that `git clone` can be done under the execution environment, so it seems that there is no problem.
Also, I confirmed that `curl -sSLO https://github.com/LAION-AI/aesthetic-predictor/blob/main/vit_b_32_embeddings/rating6.npy?raw=true` can be done under the execution environment.

**Comment by rom1504** [comment]
Do you still have that problem? All the script is doing is downloading these files.
