### ISSUE TITLE
How to use clip-retrievel on my own dataset?

### ISSUE THREAD

**Issue by YUHANG-Ma** [rom1504/clip-retrieval#153]
Hi, I meet a problem when using clip-retrieval. My dataset path is like this: /data1/train-{00000..00099}.tar. Each tar file contains .jpg and .cls which match each other. I want to use clip-retriecal to get img embedding. I run like this:

clip-retrieval inference --input_dataset /root/data0601/train-0001.tar --output_folder /root/npy0602 --input_format webdataset

I didn't encounter any issue but there is no img embed nor text embed in the output folder. Could I ask how I can fix it?
![image](https://user-images.githubusercontent.com/72591225/171370929-43cd8d43-db23-469c-86aa-da1ff539607a.png)

**Comment by rom1504** [comment]
Hi ,
You need to put the enable text option to false

**Comment by YUHANG-Ma** [comment]
It works. But when I run 
clip-retrieval inference --input_dataset /root/try_data/data0601/train-{0001..0002}.tar --output_folder /root/try_data/npy0602 --input_format webdataset --enable_text False
I got only one npy file. Is that right? I thought I need two .npy to train the decoder of dalle2.

**Comment by rom1504** [comment]
You need image and text to train a text to image model

**Comment by YUHANG-Ma** [comment]
Hi, I read the readme and it is shown as below.
![image](https://user-images.githubusercontent.com/72591225/171577337-feedcb8a-c699-4b0c-94a2-a80cd4a09b13.png)
My understanding is that training for diffusion prior and decoder parts is seperate. They combine with each other in the inference stage.

**Comment by rom1504** [comment]
Yes, but you still need text and images and images embeddings for the decoder training if you follow the dalle2 paper

You may be able to use only images and images embeddings if you remove the text conditioning

**Comment by YUHANG-Ma** [comment]
Yes, it make sense.
