### ISSUE TITLE
I can't get the GUI to do anything

### ISSUE THREAD

**Issue by articulite** [rom1504/clip-retrieval#155]
Neither the default backend or the colab sample backend appear to work.

Maybe I'm doing something wrong though.

**Comment by articulite** [comment]
looks like a cert error, at least for the default LAION. 
![image](https://user-images.githubusercontent.com/6879392/173175477-1fef087c-6238-4903-85cd-6ea4265cdfdd.png)

**Comment by rom1504** [comment]
It's fixed
