### ISSUE TITLE
Question about clip filter certain query

### ISSUE THREAD

**Issue by xilongzhou** [rom1504/clip-retrieval#158]
Hi, 

Thank you very much for the great work! It is really amazing and makes our life easier. I am working on creating subset of laion5B given certain text query and came across some issues: 

1) I firstly check this command `clip-retrieval filter --query "cat" --output_folder "cat/" --indice_folder "indice_folder"
` . and I realize that I need to do clip inference and index before running filter. If I would like to download all the examples with 'cat' query from Laion5B dataset, do I need to download the whole dataset, then run inference, index and filter to extract the meta data of "cat"? 

2) Then I check the simple_filter.ipynb file but confused about this `"/home/rom1504/indices_paths.json"`. Where can we download this json file? does it include the clip index results of all the Laion5B dataset?

I appreciate your time and help!

**Comment by rom1504** [comment]
Hi, i answered in one of the other places you asked
It does not help to send the same message in multiple issues
