### ISSUE TITLE
Problem in downloading via ClipClient

### ISSUE THREAD

**Issue by Deadsec69** [rom1504/clip-retrieval#164]
ClipClient not working with num_images more than 1000
I tried this code
` client = ClipClient(
    url="https://knn5.laion.ai/knn-service",
    indice_name="laion5B",
    aesthetic_score=9,
    aesthetic_weight=0.5,
    modality=Modality.IMAGE,
    num_images=1000,
)
`

**Comment by rom1504** [comment]
What's the error?

**Comment by Deadsec69** [comment]
This is the error 
` JSONDecodeError: Expecting value: line 1 column 1 (char 0) `

**Comment by rom1504** [comment]
Please share the full error

**Comment by Deadsec69** [comment]
https://colab.research.google.com/github/rom1504/clip-retrieval/blob/master/notebook/clip-client-query-api.ipynb#scrollTo=iMNCv6Nch652.   I was using this notebook           
from IPython.display import Image, display
from clip_retrieval.clip_client import ClipClient, Modality

IMAGE_BASE_URL = "https://github.com/rom1504/clip-retrieval/raw/main/tests/test_clip_inference/test_images/"

`
def log_result(result):
    id, caption, url, similarity = result["id"], result["caption"], result["url"], result["similarity"]
    print(f"id: {id}")
    print(f"caption: {caption}")
    print(f"url: {url}")
    print(f"similarity: {similarity}")
    display(Image(url=url, unconfined=True))

client = ClipClient(
    url="https://knn5.laion.ai/knn-service",
    indice_name="laion5B",
    aesthetic_score=9,
    aesthetic_weight=0.5,
    modality=Modality.IMAGE,
    num_images=100000,
)
`
` cat_results = client.query(text="an image of a human")
log_result(cat_results[0]) `


` ---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/requests/models.py](https://localhost:8080/#) in json(self, **kwargs)
    970         try:
--> 971             return complexjson.loads(self.text, **kwargs)
    972         except JSONDecodeError as e:

6 frames
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/requests/models.py](https://localhost:8080/#) in json(self, **kwargs)
    973             # Catch JSON-related errors and raise as requests.JSONDecodeError
    974             # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975             raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    976 
    977     @property

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by rom1504** [comment]
ah yes this is a duplicated of #160 
you currently can't get 100000 items
if you disable safety and violence and query laion400m it'll be faster

I'll fix it in #160

**Comment by dydxdt** [comment]
I met the same error when I use num_images=100. Like this:
client = ClipClient(url="https://knn.laion.ai/knn-service", indice_name="laion5B-L-14", num_images=1000)
Who knows how to solve this ? Thanks!!!
