### ISSUE TITLE
Find certain image in the dataset

### ISSUE THREAD

**Issue by D0miH** [rom1504/clip-retrieval#165]
Hi @rom1504,

first of all thanks for this awesome project. Comes in really handy :)

The problem I have is the following: I have an image and I want to check if it is occuring in the LAION-400M dataset. Using the frontend of your project I see that only similar images but not exact matches are returned. However, it would be cool to instead of only returning the KNNs to get the exact match. I figure that in this case the cosine similarity would be 1.

From reading the docs I couldn't find an option to do this using `ClipClient`. Do you maybe have any idea how I could perform exact image search?

Thanks in advance and best,
Dominik

**Comment by rom1504** [comment]
Hello,

This is based on embeddings and approximate knn. So the similarity won't be 1
You may disable aesthetic scoring and other options like safety and violence filtering to increase the chance to find an exact match

**Comment by D0miH** [comment]
Thanks for the fast answer. Disabling aesthetic scoring did the trick. I am now able to find the same image (if it exists). 

Thanks for your help 👍🏼
