### ISSUE TITLE
error when using clip-client-query-api notebook

### ISSUE THREAD

**Issue by Penguin-jpg** [rom1504/clip-retrieval#166]
I ran into JSONDecodeError: Expecting value: line 1 column 1 (char 0) when running the third cell of clip-client-query-api notebook.
I didn't change anything of the notebook. Is there any extra package need to install?

![image](https://user-images.githubusercontent.com/69071861/176994953-9a85619b-ecfd-4ebc-96e3-9abf0592d20b.png)

**Comment by rom1504** [comment]
fixed

**Comment by Penguin-jpg** [comment]
> fixed

Thanks!! it works.
