### ISSUE TITLE
Infinite scroll on frontend not working

### ISSUE THREAD

**Issue by D0miH** [rom1504/clip-retrieval#170]
Hi @rom1504,

so I got everything up and running to search through a local dataset. I can search for images using the text prompt and get reasonable results. 

However, when I scroll to the bottom, there are no additional images loaded. I can see in the console output of the backend the following lines when reaching the end of the site:
```
127.0.0.1 - - [19/Jul/2022 17:02:59] "POST //metadata HTTP/1.1" 200 -
```

Any idea what could be the cause that no additional images are loaded? 

As a little extra info: I have not specified a `--output_partition_count` when calculating the embeddings. My dataset has roughly 2 million images and the embeddings are saved into 3 .npy files. Could this be the case that there are too few partitions and therefore the process is very slow?

Thanks in advance and best,
Dominik

**Comment by rom1504** [comment]
Hi, do you observe the same when disabling safety checks and deduplication in the front end checks ?

**Comment by D0miH** [comment]
Yes, these options have no effect on the behavior as far as I can tell.

**Comment by rom1504** [comment]
Ok, can you check in chrome network tab what gets returned by knn call and metadata call ?
If one of them has few values, it's likely the problem
Also do you see many errors when trying to get images in chrome dev tools ?

**Comment by D0miH** [comment]
There seems to be no knn call when reaching the bottom of the site. In the console `fetching more metadata starting from position 39` is printed, but in the network tab only a metadata call is made. The return value of the metadata is a list with the ids and the metadata of the images.

Here is a censored screenshot of the network traffic.

![Screenshot 2022-07-20 at 08 52 30](https://user-images.githubusercontent.com/36657497/179923479-46bf278b-3705-4421-8e19-a6e457776a37.png)

**Comment by rom1504** [comment]
Yes that is expected. The KNN call is done once to get all the IDs. Then further call to metadata fetch the data from IDs.

Did you check the urls that are returned call be displayed in a browser? (IE no hot link protection+status 200)

**Comment by rom1504** [comment]
Ah don't you have urls at all in the metadata?

**Comment by D0miH** [comment]
> Ah don't you have urls at all in the metadata?

Yes, all images are local and only the path to the images is returned.

**Comment by rom1504** [comment]
Ok what gets actually displayed in this case is the 'image' field that is base64 https://github.com/rom1504/clip-retrieval/blob/main/front/src/clip-front.js#L472 and gets read by the backend from disk

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval/blob/main/clip_retrieval/clip_back.py#L158 and indeed that's not getting done in the metadata endpoint

So that's the issue, this is missing

**Comment by rom1504** [comment]
Can you try https://github.com/rom1504/clip-retrieval/pull/171 ?

**Comment by rom1504** [comment]
Fixed now
