### ISSUE TITLE
Internal Server Error when searching over text on LAION5B

### ISSUE THREAD

**Issue by D0miH** [rom1504/clip-retrieval#174]
Hi,

when searching over the LAION-5B dataset with the text modality, an internal server error occurs. However, doing the same on the LAION-400M dataset works as intended. For more debug info see the screenshots below.

Here the not working example on the LAION-5B dataset:
![Screenshot 2022-08-12 at 15 43 13](https://user-images.githubusercontent.com/36657497/184366597-b2cd8a77-1322-4343-8471-cf4dfd88f626.png)

and here the working example on the LAION-400M dataset:
![Screenshot 2022-08-12 at 15 44 00](https://user-images.githubusercontent.com/36657497/184366680-23cff0b8-dca5-4112-ac81-00844f97ad0a.png)

I hope my descriptions are helping. 

Best,
Dominik

**Comment by rom1504** [comment]
Hello, this is expected, I did not build a text index.
Do you have an use case for it ?

**Comment by D0miH** [comment]
Yeah, my use case was to find images with captions for specific actors and actresses for building a machine learning dataset. However, since the name of the actor/actress has to appear in the caption for my use case, I wanted to use the search over the text indices.

My next idea was now to use images of actors I already have and calculate the embeddings locally to not strain your server to much. Then I would get similar images with their caption and look for the name of the actor/actress in the caption and filter the returned images. In this case I would search over the image indices. But at the moment I am not able to get the command `client.query(embedding_input=embedding)` to work. I am always getting an `Internal Server Error`. 
Any idea why this might be the case? As far as I understand this should work by only using the already calculated image indices.

**Comment by rom1504** [comment]
ah, I've had to block a few ips recently because they were breaking the service. I can unblock but can you try to make queries less often and/or to use the indices locally yourself?

**Comment by D0miH** [comment]
Ah, I see. Yes, I will make less queries. Sorry for the inconvenience! 😅  
Can you tell me (maybe post a link here) where I can find the indices for downloading?

**Comment by D0miH** [comment]
Is it this one?: https://huggingface.co/datasets/laion/laion5B-index
