### ISSUE TITLE
consider adding an option in the back to fetch images in the back

### ISSUE THREAD

**Issue by rom1504** [rom1504/clip-retrieval#18]
bypass problem of images that cannot be fetched from a browser

**Comment by rom1504** [comment]
if doing that, put the site referal like `"referer": "https://www.jf-studios.com/"` as headers to bypass protection such as in https://jf-studios.com/wp-content/uploads/thon/drawing-anime-lady-kawaiiiii-anime-girl-drawing-sketch-in-2019-pinterest-drawings-of-drawing-anime-lady-300x170.jpg (do not click, NSFW outside of the website)

**Comment by rvencu** [comment]
when working with sessions I also found having to change headers for each call impacting the actual performance for too little gain...
