### ISSUE TITLE
Potential security issue in https://rom1504.github.io/clip-retrieval/

### ISSUE THREAD

**Issue by matrs** [rom1504/clip-retrieval#198]
Hey, 
This just happened to me.  I was browsing results in https://rom1504.github.io/clip-retrieval/ , and after a few seconds going though the results, this appeared in my browser:
![putorfootin.com](https://user-images.githubusercontent.com/12502882/198117658-6f4f638c-e697-450a-82a4-9d2cc0dbd504.png)

I tried a couple of times and always happened (I started searching for something like "adidas sneaker" an then clicking in random images to obtain new results)

**Comment by rom1504** [comment]
Hi, that's happens before images are hot linked and some websites are
blacklisted by chrome
There's no actual risk
We could however still use chrome black list to pre filter these domains

**Comment by matrs** [comment]
I see, thanks for the clarification :+1:
