### ISSUE TITLE
Simple improvements to front

### ISSUE THREAD

**Issue by rom1504** [rom1504/clip-retrieval#21]
* image search
* exploration by clicking on image/text icon next to each result item

**Comment by rom1504** [comment]
![image](https://user-images.githubusercontent.com/2346494/132408784-85544a3e-fc4c-4477-a98c-bf4a84f22fbd.png)
 also make it look more like that (css grid + text + img)

**Comment by TheArmagan** [comment]
How does the search by image api works?

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval/pull/25 putting the link here for reference

@TheArmagan https://github.com/rom1504/clip-retrieval#clip-back see this
basically you send an image to it and you get image/text results

**Comment by rom1504** [comment]
done
