### ISSUE TITLE
How to use downloaded KNN indices?

### ISSUE THREAD

**Issue by abelghazinyan** [rom1504/clip-retrieval#210]
Hey I want to download and locally use KNN indices for searching by queries. 
I want to use [this](https://huggingface.co/datasets/laion/laion5B-index)

How to do that?
And also how to have custom num limit.
As I want to run it locally, I don't mind having to wait for long to retrieve let's say closest 100k queries.

How is that possible?
Thanks for this amazing work!

**Comment by rom1504** [comment]
Hi, you can simply download it and give it to clip-retrieval back

**Comment by abelghazinyan** [comment]
I don't see how to initialise it, can you help me

**Comment by rom1504** [comment]
Follow this https://github.com/rom1504/clip-retrieval#clip-back

The output folder is the folder you download from hf

**Comment by rom1504** [comment]
see https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_back.md
