### ISSUE TITLE
504 response from the server

### ISSUE THREAD

**Issue by yossigandelsman** [rom1504/clip-retrieval#226]
Hi! Thanks for the great work!
I am trying to run:
```
client = ClipClient(url="https://knn5.laion.ai/knn-service",
indice_name="laion_400m",
num_images=1024,
modality=Modality.TEXT)
```
And getting:
```
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```
Is there a way to check if the server is up? It seems like currently it is not...
Thank you

**Comment by aisagarw** [comment]
I am also facing the same issue for the last few hours. It was working for me yesterday though.

**Comment by rom1504** [comment]
Blocked some ips to make it work again.

Please don't do too many calls.
If you need to do many queries, run it yourself (see readme as to how)

**Comment by jaks19** [comment]
Is it working for people now? I still get the time out.

**Comment by jaks19** [comment]
Is it working now for people?

**Comment by rom1504** [comment]
I'm guessing more people are hammering the API?

I'll have to put in place more limits if people can't behave reasonably

**Comment by jaks19** [comment]
I am doing about a dozen requests over 24 hours. I am using the tool in my research. Will it be restored anytime soon? Thanks.

**Comment by rom1504** [comment]
fixed once more

**Comment by MaxFBurg** [comment]
> Blocked some ips to make it work again. Please don't do too many calls. If you need to do many queries, run it yourself (see readme as to how)

Thank you very much for the great work! I just opened a related issue: https://github.com/rom1504/clip-retrieval/issues/229 - is anybody running the backend their selves and could help with that?

**Comment by rom1504** [comment]
fixed now
