### ISSUE TITLE
ImportError in laion5B_back.md example

### ISSUE THREAD

**Issue by MaxFBurg** [rom1504/clip-retrieval#229]
Hi @rom1504 ,

thank you very much for providing this great tool! I just tried to set up the backend myself following https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_back.md, however, there seems to be an issue with the dependencies, as I get this error:

```ImportError: cannot import name 'dataset_utils' from 'keras.preprocessing' (data_scripts/.clip_retrieval_env/lib/python3.9/site-packages/keras/preprocessing/__init__.py)```

Could you help me with that?

**Comment by rom1504** [comment]
`pip install autokeras==1.0.18 keras==2.8.0 Keras-Preprocessing==1.1.2 tensorflow==2.8.0`

**Comment by jaks19** [comment]
@rom1504 I am also following the guide at:
https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_back.md

How feasible is this if I store files on a HDD v/s SSD? Should I abandon the idea with HDD? Thanks.
