### ISSUE TITLE
Downloading the laion5b-text-index

### ISSUE THREAD

**Issue by yzou2** [rom1504/clip-retrieval#230]
Thanks a lot for sharing the laion5b-index which is of great help. I notice that only the image.index is provided. When can I download the text.index? If it's not public yet, is there a plan to release the text.index?

**Comment by rom1504** [comment]
hello, I didn't compute one

could be possible to create one

**Comment by yzou2** [comment]
Thanks for the prompt response! If you did not compute the text index, how did you do text-to-text search in the https://rom1504.github.io/clip-retrieval/

**Comment by rom1504** [comment]
on laion5B, it's not doing text-to-text, it's doing text-to-image or image-to-image based on your query
for laion400M there is text-to-text and image-to-text indeed, indices are there https://the-eye.eu/public/AI/cah/laion400m-indexes/laion400m-64GB-index/

**Comment by yzou2** [comment]
Oh, I see, thanks! Also it will be greatly appreciated if you plan to release the text index for laion 5b
