### ISSUE TITLE
From LAION5b index to more metadata

### ISSUE THREAD

**Issue by yzou2** [rom1504/clip-retrieval#233]
I have successfully retrieved the url and corresponding captions from some sample_id in the laion5b_index (https://huggingface.co/datasets/laion/laion5B-index). But looks like it does not have the image-text similarity, aesthetic score and other metadata. How can I get get these metadata based on sample_id? 

Also how do I know which subset (2b-English, 2b-nolang, 1b-mult) a sample ID in the laion5b_index belongs to?

thanks a lot for your help. I am a beginner of the code base. Your help will be definitely very useful!

**Comment by yzou2** [comment]
I think I should use the parquet meta files instead of the arrow ones to get more metadata, not just caption/url. Looks like the arrows only have these two columns

**Comment by rom1504** [comment]
You can join and regenerate the arrow files

Or you can use the aesthetic embeddings and the live inference of safety model as done in clip back

**Comment by yzou2** [comment]
Thanks for your reply! Looks like we can reconstruct the embedding from the index: https://github.com/rom1504/clip-retrieval/blob/main/clip_retrieval/clip_back.py#L358 Is the reconstructed image embedding the same as the original one or is a lossy reconstruction? Curious if the laion5b index is a flat or other approximate index

**Comment by yzou2** [comment]
Sorry I have one more question. What’s the code line  to reconstruct the embedding from the index? I only find search_and_reconstruct in clip_back. Do we need to do some reverse transform like getting centroids in https://github.com/rom1504/clip-retrieval/issues/196#issuecomment-1288224034

**Comment by rom1504** [comment]
yes search_and_reconstruct is correct
