### ISSUE TITLE
Run index locally (different CLIP models)

### ISSUE THREAD

**Issue by jaks19** [rom1504/clip-retrieval#239]
I am trying to run the index locally following [the tutorial](https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_back.md
). 

Question: 
If I want to use the index `laion5B-H-14` as demoed [here](https://knn.laion.ai/?back=https%3A%2F%2Fknn.laion.ai%2F&index=laion5B-H-14&useMclip=false), where can I download it from?

**I assume it is not the same index found here [huggingface files](https://huggingface.co/datasets/laion/laion5B-index), correct?**

Thanks!

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_h14_back.md
