### ISSUE TITLE
Disk space needed to run locally

### ISSUE THREAD

**Issue by gilmartinspinheiro** [rom1504/clip-retrieval#244]
I believe I did too many requests with CLIP Client since I am getting:
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='knn5.laion.ai', port=443): Max retries exceeded with url: /knn-service`

I believe the best approach would be to run CLIP filter locally, probably using H/14 model. Is it possible to have an estimate of the space needed in the hard drive? I know I need to download at least 1940 GB of data, but I don't know how much additional space the "index_combiner" requires.

Also, will it be impossibly slow if using an HDD instead of an SSD?

Thanks for the great work and thank you in advance for any clarification

**Comment by rom1504** [comment]
L/14 requires 2TB

H/14 indeed requires you to run the index combiner; you can first do this with a 2TB ssd, then remove the temporary file 

eventually it all fits on 2TB
