### ISSUE TITLE
When use clip-retrieval inference.worker, if the file format is webdataset and there are more than one tar file, only one file is read

### ISSUE THREAD

**Issue by AlanKang98** [rom1504/clip-retrieval#245]

**Comment by AlanKang98** [comment]
And if use clip-retrieval inference, when reading multiple files from webdataset, the torch will rise the error:
File "python3.7/site-packages/torch/utils/data/dataloader.py", line 233, in __init__ if num_workers < 0: 
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by simhermansson** [comment]
I had the problem where it only read one tar file when using clip-retrieval inference. I realized you have to use double quotes around the path to the dataset. Like "path/to/data/{000..010}.tar" instead of path/to/data/{000..010}.tar. Make sure to use = when passing arguments also.
