### ISSUE TITLE
Login password

### ISSUE THREAD

**Issue by usuyama** [rom1504/clip-retrieval#247]
Is there a way to set login password, so we can easily share the demo within a team?

Thank you for this amazing work, @rom1504 !

**Comment by rom1504** [comment]
Easiest is probably to set up a password with nginx and use a reverse proxy
towards clip retrieval back/front

**Comment by usuyama** [comment]
Thank you! We're also checking if we can deploy using Azure App Service (then it'll be easy to use more advanced authentications).
