### ISSUE TITLE
How to use the framework on my own dataset？

### ISSUE THREAD

**Issue by Itay89** [rom1504/clip-retrieval#254]
Hi, 
I have a local dataset and want to use clip-retrieval on my dataset. 
For example, do client.query(text="an image of a cat"), and search the results on my dataset (the best image of a cat).
How can I do it?
Thanks

**Comment by rom1504** [comment]
Hi, could you try following the readme for this ?
Please say if anything is unclear

**Comment by Itay89** [comment]
Hi, 
I tried to follow it. 
I created the dataset according to "Create a dataset" in the readme. 
But I don't understand how to use it. I also looked at "clip_client.py" and read the description of "query" and "__search_knn_api__", but haven't found an answear yet...

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval#clip-inference start here
