### ISSUE TITLE
About image2image retrieval on custom datasets

### ISSUE THREAD

**Issue by zbw4034** [rom1504/clip-retrieval#265]
Hi!
Thanks for your fantastic and helpful work! It's apprecated by everyone in my lab.

I plan to conduct image-to-image retrieval on my own local dataset(like Visual Genome and MSCOCO), and use knn to return several similar images. I find this function is already supported on your clip front API with webdata. I read the readme and it seems it's mainly about image-text retrieval. Could u tell me how to implement?

**Comment by rom1504** [comment]
Hi,

Glad it's helpful

The clip back code allows computing image embeddings from images the user
provides and then using that as a query for the knn index. That's image
image search

You can use clip inference with only images and it will do what you want
