### ISSUE TITLE
How to map LAION-5B's image to pre-computed CLIP embedding?

### ISSUE THREAD

**Issue by LeoXing1996** [rom1504/clip-retrieval#268]
I have already downloaded the LAION 5B dataset from https://huggingface.co/datasets/laion/laion2B-en, and now I want to use the pre-computed CLIP embedding in https://huggingface.co/datasets/laion/laion2b-en-vit-l-14-embeddings/tree/main. 

However, I found the metadata (or image order?) in those two repos are mismatched.  How can we map the clip embedding to the downloaded laion2b-en dataset?

**Comment by rom1504** [comment]
it's in the same order as the metadata there https://huggingface.co/datasets/laion/laion2b-en-vit-l-14-embeddings/tree/main/metadata

**Comment by LeoXing1996** [comment]
@rom1504, thanks for your answer! 

I apologize if my question was unclear. I am seeking guidance on how to align the metadata for CLIP embeddings with the metadata for LAION-2b-en.
e.g.
<img width="1512" alt="image" src="https://github.com/rom1504/clip-retrieval/assets/28132635/33854a50-214e-46d7-a38f-e5035aa181e8">

Can you provide any assistance with this matter?

**Comment by rom1504** [comment]
What is the purpose of doing that?

The metadata next to the embeddings is also the laion2B metadata but in a different order

**Comment by LeoXing1996** [comment]
@rom1504, I have already downloaded the LAION-2b-en and converted it to webdataset's style. 

If I want to load the pre-computed CLIP embedding with the image during training, one good practice is to resort the CLIP embedding file and make it align with the images in tar files.

**Comment by rom1504** [comment]
Ok see
https://github.com/lucidrains/DALLE2-pytorch#decoder-image-embedding-dataset

And in particular https://github.com/Veldrovive/embedding-dataset-reordering

**Comment by DJLee68** [comment]
did u solve this? @LeoXing1996

**Comment by DJLee68** [comment]
> > did u solve this? @LeoXing1996
> 
> @DJLee68, no, I recalculate all embeddings by myself 😢

I'm having the same problem.


> Ok see
https://github.com/lucidrains/DALLE2-pytorch#decoder-image-embedding-dataset
>
> And in particular https://github.com/Veldrovive/embedding-dataset-reordering

I tried using these repos from above which @rom1504 mentioned, but they didn't work for us.


so did u match whole [embedding of laion-2b](https://the-eye.eu/public/AI/cah/laion5b/embeddings/laion2B-en/img_emb/) with laion-2b img webdataset using [meta data of laion-2b](https://the-eye.eu/public/AI/cah/laion5b/metadata/laion2B-en/)?
