### ISSUE TITLE
504 Gateway time out error (again)

### ISSUE THREAD

**Issue by m3lionas** [rom1504/clip-retrieval#270]
Hi, seems that the 504 gateway time-out issue is happening yet again.
Same problem as [issue 267](https://github.com/rom1504/clip-retrieval/issues/267)

**Comment by epicshardz** [comment]
JSONDecodeError: [Errno Expecting value] <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>

**Comment by sayakpaul** [comment]
Hmm can reproduce:

```python
from clip_retrieval.clip_client import ClipClient

num_images = 5
client = ClipClient(
    url="https://knn.laion.ai/knn-service", indice_name="laion_400m", num_images=num_images, aesthetic_weight=0.1
)

results = client.query(text="a an image of a dog")
```

**Comment by rom1504** [comment]
back

sorry if people hit the service too hard it'll go down; this is a best effort service
