### ISSUE TITLE
The column of "similarity" meaning?

### ISSUE THREAD

**Issue by ArlanCooper** [rom1504/clip-retrieval#273]
I want to know, how is the similarity between text and images calculated here? Is cosine similarity used? The cosine similarity calculated by me is inconsistent with the values stored in the data:
there is one data like this:

('blond woman wearing jewelry stock photo',
   0.5808565020561218,
   'http://media.istockphoto.com/photos/blond-woman-wearing-jewelry-picture-id157528193?k=6&amp;m=157528193&amp;s=612x612&amp;w=0&amp;h=oVM194R_VeLK5BOwIBkpI3n-NW30StYIQjuiMFgIyX8=')

but, i calculated  the similarity, it's not 0.5808565020561218:
```python
def similarity_cos(a,b):
  return a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

i_e = get_image_emb("http://media.istockphoto.com/photos/blond-woman-wearing-jewelry-picture-id157528193?k=6&amp;m=157528193&amp;s=612x612&amp;w=0&amp;h=oVM194R_VeLK5BOwIBkpI3n-NW30StYIQjuiMFgIyX8=")
t_e1 = get_text_emb("blond woman wearing jewelry stock photo")
s1 = similarity_cos(i_e,t_e1)

```
the ans is 0.34096664

can you tell me the reason,please?

**Comment by rom1504** [comment]
It's approximate similarity, computed by faiss
For some pairs it might be different than absolute value but overall keeping a similar ordering

**Comment by ArlanCooper** [comment]
> It's approximate similarity, computed by faiss For some pairs it might be different than absolute value but overall keeping a similar ordering

thank you, i understand it.
