### ISSUE TITLE
About Text Retrieval Images on Custom Datasets

### ISSUE THREAD

**Issue by tingyumoxing** [rom1504/clip-retrieval#274]
Hi!
Thanks for your fantastic and helpful work! I am very grateful.

Based on your note: clip retrieval getting started ipynb, I plan to conduct text to image searches on my own local dataset. Finally, it was found that the searched images did not correspond to the text and were all displayed.
My embedding_folder already exists in img_emb_ 0.npy and text_emb_0.npy, I don't know where the setup went wrong. Thank you for your guidance.

![图片](https://github.com/rom1504/clip-retrieval/assets/129018257/1973992b-5de0-4201-b391-fa46315530e6)
![图片](https://github.com/rom1504/clip-retrieval/assets/129018257/734984f8-1d22-423a-82bd-ed53348cd6c6)

**Comment by rom1504** [comment]
do 000.jpg and 000.txt match ?
