### ISSUE TITLE
Laion5B knn-service indice name

### ISSUE THREAD

**Issue by varunnrao** [rom1504/clip-retrieval#278]
I've followed the instructions [here](https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_back.md) for running clip-retrieval back with laion5B index. 

However, whenever I run the service and create a client as 
`client = ClipClient(url="http://127.0.0.1:1234/knn-service", indice_name="laion5B-L-14")`, I get a POST 500 error `KeyError: 'laion5B-L-14'`
What is the right `indice_name` is?

**Comment by rom1504** [comment]
the one you put in the .json file for indices

**Comment by rom1504** [comment]
the one you put in the .json file for indices
