### ISSUE TITLE
Best way of merging indices

### ISSUE THREAD

**Issue by tomvars** [rom1504/clip-retrieval#280]
Hi!

First of all, thank you for open-sourcing this fantastic project.

I'm running clip-retrieval on an initial 200k images (stored locally in a server). I used img2dataset with `files` output format and it created 17 separate image folders. After running inference and indexing separately I've hit a wall with the `index_combiner` running into the following:

```
26         # the total size of the inverted lists can exceed the
     27         # available RAM
     28         LOG.info("read " + fname)
     29         index = faiss.read_index(fname, faiss.IO_FLAG_MMAP)
---> 30         index_ivf = faiss.extract_index_ivf(index)
     31         ivfs.append(index_ivf.invlists)
     32 
     33         # avoid that the invlists get deallocated with the index

[~/.venv/lib/python3.8/site-packages/faiss/swigfaiss_avx2.py] in ?(*args)
   5793 def extract_index_ivf(*args):
-> 5794     return _swigfaiss_avx2.extract_index_ivf(*args)

RuntimeError: Error in const faiss::IndexIVF* faiss::ivflib::extract_index_ivf(const faiss::Index*) at [/project/faiss/faiss/IVFlib.cpp:82](https://vscode-remote+ssh-002dremote-002bdodo.vscode-resource.vscode-cdn.net/project/faiss/faiss/IVFlib.cpp:82):
```

If you have any clues what could be going wrong it would be really appreciated 🙏  or otherwise, if there is a better way of running this pipeline - e.g using img2dataset with webdataset instead of files and changing the way this is passed to clip-inference?

**Comment by rom1504** [comment]
this is likely to be caused by your environment

if you still need to fix this, please post details on your env (os, version of python, ...) and re open
