### ISSUE TITLE
ModuleNotFoundError: No module named 'clip_client'

### ISSUE THREAD

**Issue by Alby0n** [rom1504/clip-retrieval#285]
from clip_client import Client as ClipClient
ModuleNotFoundError: No module named 'clip_client'

**Comment by Alby0n** [comment]
from clip_retrieval.clip_client import ClipClient is not found in modules

**Comment by adaxidedakaonang** [comment]
Met same problem

**Comment by lianakoleva** [comment]
same problem

**Comment by adaxidedakaonang** [comment]
> 

Copying the folder "clip_retrieval" into your project can solve the problem

**Comment by rom1504** [comment]
the module name is not clip_client
