### ISSUE TITLE
Issue in setting up clip-back with an H/14 index of Laion5B

### ISSUE THREAD

**Issue by adtygan** [rom1504/clip-retrieval#286]
I am following the guide mentioned in [https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_h14_back.md](https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_h14_back.md) and I ran into an error in step 7, for the command 

`clip-retrieval parquet_to_arrow --parquet_folder="en-embeddings" --output_arrow_folder="en-combined" --columns_to_return='["url", "caption"]'`

The error I get is

<img width="1060" alt="Screenshot 2023-06-18 at 4 43 51 PM" src="https://github.com/rom1504/clip-retrieval/assets/51450254/e203dfa2-7916-44fe-8afa-563bc07cfbe7">

I have inspected the value for the variable `key_format` and its -2 for me. Am I running into an error because the code expects a non-negative number?

I must also mention that before running this command, I had manually appended `.parquet` to all the embeddings that got downloaded in step 6. I did this because the code used in step 7 looks for files with `.parquet` extension and none of the downloaded embeddings had that extension.

**Comment by rom1504** [comment]
Hi, the problem is you need to download the parquet files that contain the
metadata.
The npy files are not the metadata

**Comment by adtygan** [comment]
This is the command that I ran to download the parquet files 

`clip-retrieval parquet_to_arrow --parquet_folder="en-embeddings" --output_arrow_folder="en-combined" --columns_to_return='["url", "caption"]'`

I think I have found the error. When the `key_format` is a negative number it returns this error. And the reason it was negative for me was because I was trying to download just the first 12 parquet files as a test. 

The error stems from [clip_retrieval/clip_back_prepro/parquet_to_arrow.py](clip_retrieval/clip_back_prepro/parquet_to_arrow.py)'s line 39 where the `key_format` variable's value is set. 

`L39: key_format = int(math.log10(number_samples / 10**10)) + 1` 

My `num_samples` is 12195418. and Dividing it by 10^10 leads to a negative number and hence the error. I'm guessing if I download the entire set of parquet files, the `num_samples` is going to be higher than 10^10 and therefore avoid this error.

**Comment by rom1504** [comment]
This command doesn't download any files. You need to run something like wget

**Comment by adtygan** [comment]
I'm sorry I referenced the wrong command. As mentioned in step 6 of the guide in [https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_h14_back.md](https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_h14_back.md), I used the command 

`for i in {0000..2314}; do aria2c -x 16 https://huggingface.co/datasets/laion/laion2b-en-vit-h-14-embeddings/resolve/main/metadata/metadata_$i.parquet; done` 

to download the parquet files. This is the correct one?

**Comment by marson666** [comment]
@rom1504 Another question, i build laion5B_h14_back successful locally, when i use clip_client search
`client = ClipClient(
    url="http://127.0.0.1:1234/knn-service",
    indice_name="laion5B-H-14",
    aesthetic_score="",
    aesthetic_weight=0.5,
    modality=Modality.IMAGE,
    num_images=100,
)

cat_results = client.query(text="a man is running")
`
the cat results seems very unrelated with the query "running", how to debug this problem?

`
>>> cat_results[0]
{'caption': 'Jaké jsou vaše polibky podle znamení zvěrokruhu?', 'url': 'https://mujhoroskop.com/uploads/large_maxresdefault__4_1.jpg', 'id': 3139204416, 'similarity': 0.4006364643573761}
`

`
{'caption': 'Bouquet mariee bleu et blanc', 'url': 'https://cdn0.mariages.net/emp/fotos/4/7/1/4/bouquet-mariee-bleu-roi-blanc-fb_3_164714-161503496212461.jpg', 'id': 2441974434, 'similarity': 0.398070752620697}
`

`
{'caption': 'Monachus Hotels & Spa****', 'url': 'https://uk.zooverresources.com/images/PH136553L1W125H94RT2/Monachus-Hotels-and-Spa.jpg', 'id': 2487402917, 'similarity': 0.39280033111572266}
`

**Comment by adtygan** [comment]
@marson666 could you please mention the command you used to start `clip_back` service? I always run into `pyarrow.lib.ArrowInvalid: Must pass at least one table` this error.

**Comment by marson666** [comment]
> @marson666 could you please mention the command you used to start `clip_back` service? I always run into `pyarrow.lib.ArrowInvalid: Must pass at least one table` this error.

in indices_paths.json, you should make the input_folder according to the actual folder which contains your index and metadata files. So there is a typo,  `"indice_folder": "Laion5B_H14",` not `"indice_folder": "laion5B_H14",`   letter l should be upper L

**Comment by adtygan** [comment]
@marson666  thanks for the reply. I did change this. My command is 

`clip-retrieval back --clip_model="ViT-L/14" --default_backend="http://localhost:1234/" --port 1234 --indices-paths indices.json --use_arrow True --enable_faiss_memory_mapping True --columns_to_return='["url", "caption", "md5"]'`

 and my`indices.json` is 
 
 ```
 {
 "laion5B-H-14": {
            "indice_folder": "Laion5B_H14",
            "provide_safety_model": false,
            "enable_faiss_memory_mapping": true,
            "use_arrow": true,
            "enable_hdf5": false,
            "reorder_metadata_by_ivf_index": false,
            "columns_to_return": ["url", "caption"],
            "clip_model": "ViT-L/14",
            "enable_mclip_option": false
    }
}
```

**Comment by adtygan** [comment]
I was able to fix the error. The `arrow_folder` variable in `class ArrowMetadataProvider` was assigned the relative path and not absolute path. Fixed it by manually assigning global path.

**Comment by marson666** [comment]
> I was able to fix the error. The `arrow_folder` variable in `class ArrowMetadataProvider` was assigned the relative path and not absolute path. Fixed it by manually assigning global path.

is your query results as expected?

**Comment by rom1504** [comment]
I think it would be quite helpful for users to have a guide on running this
for a small subset of the data. Maybe you could contribute on that

**Comment by adtygan** [comment]
I just downloaded the first 10 indices and embeddings. They aren't an exact match. That is why I'm only getting the indices for most of them but not the the URLs. But what you suggest looks interesting. I will look into this and make a contribution if I get it right.
