### ISSUE TITLE
[May Bug] Distributed inference GPU management

### ISSUE THREAD

**Issue by Isaachhh** [rom1504/clip-retrieval#292]
When using Spark to infer CLIP embedding ([tutorial](https://github.com/rom1504/clip-retrieval/blob/main/docs/distributed_clip_inference.md)), I found that all tasks were offloaded to GPU:0 and all other 7 gpus on the nodes kept idle.

I doubt that it's caused by the code on [clip_retrieval/clip_inference/distributor.py Line 55](https://github.com/rom1504/clip-retrieval/blob/main/clip_retrieval/clip_inference/distributor.py#L55).
`os.environ["CUDA_VISIBLE_DEVICES"] = gpu`

to assign tasks to gpus correctly, it should be `torch.cuda.set_device(int(gpu))`

**Comment by rom1504** [comment]
Are you using spark 3 ?

Spark 2 doesn't have support for the GPU resource

**Comment by Isaachhh** [comment]
Yes.
 
The bug can be re-produced on both Spark 3.2  and Spark 3.4

**Comment by rom1504** [comment]
Do you have GPU resources set up in your spark cluster?

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval/blob/main/docs/distributed_clip_inference.md#start-the-worker-nodes example of how to do it

**Comment by Isaachhh** [comment]
Following the tutorial, I started a spark cluster with one master node and four workder nodes, 8 gpus per worker node and **32** at all.

when using `os.environ["CUDA_VISIBLE_DEVICES"] = gpu`, on each worker node,  **only 1 gpu (cuda:0) was used**, namely, 4 gpus working and 28 left idle.

but, using `torch.cuda.set_device(int(gpu))`, **all 32 gpus worked** as expection.

As https://discuss.pytorch.org/t/os-environ-cuda-visible-devices-not-functioning/105545/4 said, 

> The CUDA_VISIBLE_DEVICES environment variable is read by the cuda driver. So it needs to be set before the cuda driver is initialized. It is best if you make sure it is set before importing torch (or at least before you do anything cuda related in torch).

I doubt that `os.environ["CUDA_VISIBLE_DEVICES"] = gpu` in an improper position caused that only `cuda:0` is visible.

**Comment by BIGBALLON** [comment]
Hi, @rom1504 , is there a simple way to  inference with a single machine with multi-GPUs (e.g. 1 machine with 8 GPUs)

**Comment by rom1504** [comment]
yes you can follow the instructions above and in the readme
