### ISSUE TITLE
How to use my finetuned open-clip model?

### ISSUE THREAD

**Issue by czczup** [rom1504/clip-retrieval#294]
Thanks for your awesome work!

I use the open-clip model ('xlm-roberta-base-ViT-B-32', 'laion5b_s13b_b90k') as initialization, and fine-tune the model on my custom image-text dataset. 

After that, I got many checkpoints like `open_clip/work_dirs/2023_07_24-23_01_12-model_xlm-roberta-base-ViT-B-32-lr_1e-05-b_512-j_8-p_amp/checkpoints/epoch_30.pt`. How can I use this model to build a retrieval backend.

**Comment by czczup** [comment]
As far as I know, I should run clip inference first, like this:
```
clip-retrieval inference --input_dataset ./data --output_folder ./data_embeddings --clip_model "open_clip:xlm-roberta-base-ViT-B-32"
```

Is there any way I can load my own finetuned weights here?

**Comment by czczup** [comment]
Maybe I should modify some code to load my weights.

<img width="1027" alt="image" src="https://github.com/rom1504/clip-retrieval/assets/23737120/9f91df27-ebfb-4ddd-b826-67545ee7cd65">

**Comment by fabiozappo** [comment]
Hello there! I'm currently attempting to execute the end-to-end clip retrieval utilizing a finetuned checkpoint of openclip/xlm-roberta-base-vitb32. However, I'm encountering unusual outcomes on the frontend page. Did you encounter any bugs in the code or face similar challenges that you could provide insights on or recommend how to address?

**Comment by IF-chan** [comment]
hello how do you load your finetuned weights?
