### ISSUE TITLE
Feature Request: Image-to-Image Search Extension

### ISSUE THREAD

**Issue by FangzhengHu** [rom1504/clip-retrieval#296]
As a user of the amazing CLIP Front tool, I have found it incredibly helpful in finding relevant images based on textual queries. However, I believe this tool has even greater potential if it could be extended to support Image-to-Image Search using the same underlying CLIP embedding technique.

The current functionality allows me to input text and obtain semantic similar images, which is fantastic for various use cases. However, there are instances when I have a specific image in mind and wish to find semantic similar images from the dataset. By enabling Image-to-Image Search, I could simply upload an image, and the tool would return a list of visually similar images present in the dataset.
[](url)
The proposed extension would not only enhance the versatility of the existing tool but also make it even more powerful for various creative projects, design tasks, and content generation purposes. It could be beneficial for artists, designers, and researchers alike.

I understand that implementing this feature may involve additional complexities, such as image preprocessing and handling image embeddings. However, given the success of the current Text-to-Image Search feature, I believe that adding Image-to-Image Search would be a significant step forward.

**Comment by adtygan** [comment]
This has already been implemented. Just click on the camera button next to the search button to upload you image and then hit the search button.

<img width="1512" alt="Screenshot 2023-07-29 at 1 51 56 AM" src="https://github.com/rom1504/clip-retrieval/assets/51450254/0fdb54d7-9565-454e-b812-c752cca584d8">

**Comment by FangzhengHu** [comment]
> This has already been implemented. Just click on the camera button next to the search button to upload your image and then hit the search button.
> 
> <img alt="Screenshot 2023-07-29 at 1 51 56 AM" width="1512" src="https://user-images.githubusercontent.com/51450254/256896525-0fdb54d7-9565-454e-b812-c752cca584d8.png">

This is awesome! Thanks for the clarification!
