### ISSUE TITLE
UnidentifiedImageError

### ISSUE THREAD

**Issue by hj611** [rom1504/clip-retrieval#298]
PIL.UnidentifiedImageError: cannot identify image file
I get an error when I do inference on my own dataset. Is there anything I can do to fix it？

the log：
  image_tensor = self.image_transform(Image.open(image_file))
  File "python3.9/site-packages/PIL/Image.py", line 3030, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'dataset/img_vg/53.jpg'

**Comment by rom1504** [comment]
it means this is not a jpg
