### ISSUE TITLE
OSError: /usr/local/python/lib/python3.7/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

### ISSUE THREAD

**Issue by zccoder** [rom1504/clip-retrieval#302]
While I has installed the clip-retrieval, and then run the client.query, the problem as the title showd has occurred. The errors in detail is below:

<img width="1736" alt="image" src="https://github.com/rom1504/clip-retrieval/assets/11350088/9f2cb47e-b9fb-45cf-b311-6e62627cbdf9">

I wonder if this project need special cudnn or Cuda version, please give me an answer.  Thx a lot.

**Comment by rom1504** [comment]
try again now
