### ISSUE TITLE
Installation issues due to requirement of scipy<1.9.2 

### ISSUE THREAD

**Issue by rushi-the-neural-arch** [rom1504/clip-retrieval#303]
This is more of a scipy instllation issue, but is it possible to upgrade the scipy requirement to 1.11+ ? Tried installation on x86_64 system by running `pip install clip-retrieval` when I faced this error 

` subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1.
`
>ninja: build stopped: subcommand failed.
      + meson setup --native-file=/tmp/pip-install-8_9j25k3/scipy_cf24f13428634d55b63cf61b989bc5b8/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=/home/jupyter-rushi.parmar@hopin-770d1/.conda/envs/generative-ai /tmp/pip-install-8_9j25k3/scipy_cf24f13428634d55b63cf61b989bc5b8 /tmp/pip-install-8_9j25k3/scipy_cf24f13428634d55b63cf61b989bc5b8/.mesonpy-65cfg5l2/build
      + meson compile
      Traceback (most recent call last):
        ...............
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['meson', 'compile']' returned non-zero exit status 1.
      [end of output]
  
> note: This error originates from a subprocess, and is likely not a problem with pip.
>     error: subprocess-exited-with-error
>     × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> See above for output.

**Comment by josejhlee** [comment]
I feel you

**Comment by rom1504** [comment]
Sure, open a PR and if it passes tests let's do it

**Comment by rom1504** [comment]
fixed
