### ISSUE TITLE
Local query with KnnService

### ISSUE THREAD

**Issue by mikonvergence** [rom1504/clip-retrieval#308]
I want to replace the client queries to the remote server, like this one:
```python
client = ClipClient(url="https://knn.laion.ai/knn-service",
                    num_images=20,
                    deduplicate=True,
                    indice_name="laion5B-L-14"
                   )

results = client.query(embedding_input=image_emb.tolist())
```
with a locally run index.

My impression was that a local `KnnService` could do this, as demonstrated here:
https://github.com/rom1504/clip-retrieval/blob/main/notebook/simple_filter.ipynb

but then, the instructions linked for the `laion5B-index` dataset on HF (https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_back.md) do not mention the use of the index files directly in Python.

When I try to run:
```python
columns = ["url", "caption"]
indices_loaded, indices, device, model, preprocess, mclip_model = load_clip_indices("indices_paths.json", True, True, columns, False)
knn_service = KnnService(indices_loaded=indices_loaded, device=device, model=model, preprocess=preprocess, columns_to_return=columns, metadata_is_ordered_by_ivf=False, mclip_model=mclip_model)
```
It appears that the interface has changed since then (`load_clip_indices() takes 2 positional arguments but 5 were given`).

What would be the recommended way to run local queries from my own scripts? Is there any documentation for this that works with the current version of `clip-retrieval`?

**Use case: embedding-based query for about 4,000 embeddings, each query with up to 10k results if possible (1k per query would be fine too)**

**Comment by mikonvergence** [comment]
In case anyone is wondering, you can still use `ClipClient` with a locally run index:

```python
client = ClipClient(url="0.0.0.0:1234/knn-service",
                    num_images=20,
                    deduplicate=True,
                    indice_name="laion5B-L-14"
                   )

results = client.query(embedding_input=image_emb.tolist())
```
if you serve your index at `0.0.0.0:1234`.

You can serve from the command line as instructed here: https://github.com/rom1504/clip-retrieval/blob/main/docs/laion5B_back.md.

**Comment by rom1504** [comment]
Simple filter way should work as well, let's update and test this notebook

**Comment by FlimFlamm** [comment]
Had a gander at this; looks like previously the `ClipOptions` class did not exist, the addition of which caused the notebook's usage of `ClipClient()` to bork. Here's a quick example oh how it might be updated

```py
import os
os.environ["CUDA_VISIBLE_DEVICES"]=""
from clip_retrieval.clip_back import load_clip_indices, KnnService, ClipOptions


# setup clip options
clip_options = ClipOptions(
    indice_folder = "/home/chris/Documents/clip_client/Laion5B_H14",
    clip_model = "open_clip:ViT-H-14",
    enable_hdf5 = False,
    enable_faiss_memory_mapping = True,
    columns_to_return = ["url", "caption"],
    reorder_metadata_by_ivf_index = False,
    enable_mclip_option = False,
    use_jit = False,
    use_arrow = True,
    provide_safety_model = False,
    provide_violence_detector =  False,
    provide_aesthetic_embeddings =  False,
)

# load indices
loaded_indices = load_clip_indices("/home/chris/Documents/clip_client/indices_paths.json", clip_options)

# erect the knn search object
knn_service = KnnService(clip_resources=loaded_indices)

# filter a subset
results = knn_service.query(text_input="watermark",
                            modality="image", 
                            indice_name="laion5B-H-14", 
                            num_images=100, 
                            num_result_ids=100)
import pprint
pprint.pprint(results)
```

**Comment by FlimFlamm** [comment]
> Simple filter way should work as well, let's update and test this notebook

Updated the simple_filter.ipynb notebook just to get it working again; make a PR. You might wanna have a look at the ClipOptions()  params that I supplied, as I'm not sure what is appropriate for the default /common case.
