### ISSUE TITLE
can't run filter with "--threshold"?

### ISSUE THREAD

**Issue by laolongboy** [rom1504/clip-retrieval#319]
```
# run successfully
clip-retrieval filter \
    --query ${query_text} \
    --output_folder ${output_folder}/${query_text} \
    --indice_folder ${index_folder} \
    --num_results 100

# error when setting "--threshold"
clip-retrieval filter \
    --query ${query_text} \
    --output_folder ${output_folder}/${query_text} \
    --indice_folder ${index_folder} \
    --num_results 100 \
    --threshold 0.1
```

Error message:
RuntimeError: Error in virtual void faiss::Index::range_search(faiss::idx_t, const float*, float, faiss::RangeSearchResult*, const faiss::SearchParameters*) const at /project/faiss/faiss/Index.cpp:33: range search not implemented

**Comment by rom1504** [comment]
you need to use an index implementing this

for example a flat index can do it, IVF should be able to as well
