### ISSUE TITLE
[BUG] File loss when there are images with the same name in different folders

### ISSUE THREAD

**Issue by BIGBALLON** [rom1504/clip-retrieval#321]
Hi, @rom1504 , thanks for your great tools clip-retrieval, I find some bugs when I use clip inference API.

From  [clip_inference/reader.py](https://github.com/rom1504/clip-retrieval/blob/746e907dc52b20a2c1a8c26b0e5757c6dd58d17c/clip_retrieval/clip_inference/reader.py)
https://github.com/rom1504/clip-retrieval/blob/746e907dc52b20a2c1a8c26b0e5757c6dd58d17c/clip_retrieval/clip_inference/reader.py#L10-L31

If there are files with the same name in different folders, the function may encounter issues. This is because the function uses the file names (without extension) as keys in dictionaries to identify and organize the files. If there are files with the same name in different folders, they will collide when added to the dictionaries, and only one of them will be stored.

I think we can solve this problem by using a key that won't conflict
or just use the entire path as the key
``` python
        # image_files = {image_file.stem: image_file for image_file in image_files}
        # image_files = {image_file.relative_to(path).as_posix(): image_file for image_file in image_files}
        # image_files = {str(image_file): image_file for image_file in image_files}
```

**Comment by rom1504** [comment]
feel free to open a PR

**Comment by BIGBALLON** [comment]
@rom1504 here is  the PR https://github.com/rom1504/clip-retrieval/pull/329
