### ISSUE TITLE
Downloaded Clip embedding size not 768

### ISSUE THREAD

**Issue by xilongzhou** [rom1504/clip-retrieval#325]
Hi,

I download Clip embedding of Laion Datasaet directly from [this link](https://the-eye.eu/public/AI/cah/laion400m-met-release/laion400m-embeddings/), but the size of each image or text embedding is 512 not 768. But I recompute the clip embedding using `clip-retrieval inference` and it gives 512. Why does this happen?

Thanks for your help!

**Comment by rom1504** [comment]
512 is the dimension of the B/32 embeddings
768 is the dimension of the L/14 embeddings

**Comment by xilongzhou** [comment]
I see. Thanks for your prompt reply! Can I download the  L/14 embeddings of Laion Dataset from somewhere?

**Comment by rom1504** [comment]
currently no https://laion.ai/notes/laion-maintanence/ but hopefully soon yes
