### ISSUE TITLE
No Retrieval on https://rom1504.github.io/clip-retrieval/

### ISSUE THREAD

**Issue by Thesemar** [rom1504/clip-retrieval#327]
For several days the website doesn't seem to function at all. It won't load indexes, and by extension images. It's just empty black boxes for the indexes. Searching and waiting, no matter how patiently, doesn't result in it loading the indexes or any images.

**Comment by rom1504** [comment]
yes, see https://github.com/rom1504/clip-retrieval/issues/324

**Comment by Thesemar** [comment]
Ah okay thank you, I hadn't seen that.
