### ISSUE TITLE
Access to laion5B-index temporarily disabled

### ISSUE THREAD

**Issue by christopher-kuhn** [rom1504/clip-retrieval#349]
Hi,

Great repo! When trying to download the index on huggingface, it says access to this dataset has been temporarily disabled on the author's request: https://huggingface.co/datasets/laion/laion5B-index

Could you give some insights into when the index will be available again, or why it is currently unavailable? Thank you!

**Comment by Maxwells-Demons** [comment]
Please see https://laion.ai/notes/laion-maintanence/ and https://github.com/rom1504/clip-retrieval/issues/324
That was absurd...

**Comment by christopher-kuhn** [comment]
Thank you!
