### ISSUE TITLE
Error: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Radniforg** [rom1504/clip-retrieval#355]
Hello. 
Since new year, can't make clip-retrieval work, it drops with inner mistake.
Code:
`from IPython.display import Image, display
from clip_retrieval.clip_client import ClipClient, Modality
from datetime import datetime
import glob

IMAGE_BASE_URL = "https://github.com/rom1504/clip-retrieval/raw/main/tests/test_clip_inference/test_images/"

def log_result(result):
    id, caption, url, similarity = result["id"], result["caption"], result["url"], result["similarity"]
    print(f"id: {id}")
    print(f"caption: {caption}")
    print(f"url: {url}")
    print(f"similarity: {similarity}")
    display(Image(url=url, unconfined=True))

client = ClipClient(
    url="https://knn.laion.ai/knn-service",
    # indice_name="laion-400m",
    indice_name="laion5B-L-14",
    # indice_name="laion5B-H-14",
    aesthetic_score=9,
    aesthetic_weight=0.5,
    modality=Modality.IMAGE,
    num_images=10,
)
beach_results = client.query(image="https://github.com/rom1504/clip-retrieval/raw/main/tests/test_clip_inference/test_images/321_421.jpg")
log_result(beach_results[0])
`

Error text:
`JSONDecodeError: Expecting value: line 1 column 1 (char 0)
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File ~/.local/lib/python3.8/site-packages/requests/models.py:971, in Response.json(self, **kwargs)
    970 try:
--> 971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File /usr/lib/python3/dist-packages/simplejson/__init__.py:518, in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, use_decimal, **kw)
    514 if (cls is None and encoding is None and object_hook is None and
    515         parse_int is None and parse_float is None and
    516         parse_constant is None and object_pairs_hook is None
    517         and not use_decimal and not kw):
--> 518     return _default_decoder.decode(s)
    519 if cls is None:

File /usr/lib/python3/dist-packages/simplejson/decoder.py:370, in JSONDecoder.decode(self, s, _w, _PY3)
    369     s = str(s, self.encoding)
--> 370 obj, end = self.raw_decode(s)
    371 end = _w(s, end).end()

File /usr/lib/python3/dist-packages/simplejson/decoder.py:400, in JSONDecoder.raw_decode(self, s, idx, _w, _PY3)
    399         idx += 3
--> 400 return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 beach_results = client.query(image="https://github.com/rom1504/clip-retrieval/raw/main/tests/test_clip_inference/test_images/321_421.jpg")
      2 log_result(beach_results[0])

File ~/.local/lib/python3.8/site-packages/clip_retrieval/clip_client.py:87, in ClipClient.query(self, text, image, embedding_input)
     85 elif image:
     86     if image.startswith("http"):
---> 87         return self.__search_knn_api__(image_url=image)
     88     else:
     89         assert Path(image).exists(), f"{image} does not exist."

File ~/.local/lib/python3.8/site-packages/clip_retrieval/clip_client.py:131, in ClipClient.__search_knn_api__(self, text, image, image_url, embedding_input)
    129         encoded_string = base64.b64encode(image_file.read())
    130         image = str(encoded_string.decode("utf-8"))
--> 131 return requests.post(
    132     self.url,
    133     data=json.dumps(
    134         {
    135             "text": text,
    136             "image": image,
    137             "image_url": image_url,
    138             "embedding_input": embedding_input,
    139             "deduplicate": self.deduplicate,
    140             "use_safety_model": self.use_safety_model,
    141             "use_violence_detector": self.use_violence_detector,
    142             "indice_name": self.indice_name,
    143             "use_mclip": self.use_mclip,
    144             "aesthetic_score": self.aesthetic_score,
    145             "aesthetic_weight": self.aesthetic_weight,
    146             "modality": self.modality,
    147             "num_images": self.num_images,
    148             # num_results_ids is hardcoded to the num_images parameter.
    149             "num_result_ids": self.num_images,
    150         }
    151     ),
    152 ).json()

File ~/.local/lib/python3.8/site-packages/requests/models.py:975, in Response.json(self, **kwargs)
    971     return complexjson.loads(self.text, **kwargs)
    972 except JSONDecodeError as e:
    973     # Catch JSON-related errors and raise as requests.JSONDecodeError
    974     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 975     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by hknguyen20** [comment]
#324 because the URL you entered is down, so does not return anything

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval/issues/324
