### ISSUE TITLE
Front UI Error when deployed locally

### ISSUE THREAD

**Issue by hawaiiansun** [rom1504/clip-retrieval#357]
Hi Romain, 

I am facing some problem with the Flask UI, and the error message looks like this: 

```
<IP> - - [05/Feb/2024 19:43:07] "GET / HTTP/1.1" 304 -
<IP> - - [05/Feb/2024 19:43:07] "GET /vendor/webcomponents-loader.js HTTP/1.1" 404 -
<IP> - - [05/Feb/2024 19:43:07] "GET /vendor/custom-elements-es5-adapter.js HTTP/1.1" 404 -
<IP> - - [05/Feb/2024 19:43:07] "GET /main.6da1f410.js HTTP/1.1" 404 -
```

But I do have `/vendor/webcomponents-loader.js`, `/vendor/custom-elements-es5-adapter.js`, and `/main.6da1f410.js` in the right directory: 
<img width="401" alt="image" src="https://github.com/rom1504/clip-retrieval/assets/137232421/b69da7df-9c3e-4295-b4cd-bac408ab00f4">

I installed the front end module using these command: 

```
cd front
npm install
npm run build
cd ..
pip install -e .
```

And the command I am using to run the end2end image retrieval: 

```
clip-retrieval end2end <parquet files directory> <embedding and index output path>
```

Could you help me resolve this error? I have been bugged for several days on this. Thank you!

**Comment by hawaiiansun** [comment]
Resolved

**Comment by rom1504** [comment]
Hey what was the issue?

**Comment by hawaiiansun** [comment]
Oh, never mind. I made a mistake on my server.
