### ISSUE TITLE
UI down?

### ISSUE THREAD

**Issue by bkj** [rom1504/clip-retrieval#362]
Is the UI down?  Previously the `Index:` dropdown would populate but now it doesn't:

![screenshot - 2024-02-21 at 11 25 54 AM](https://github.com/rom1504/clip-retrieval/assets/6086781/634e510b-d35b-4e79-955d-8d20407c39a2)

Thanks!

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval/issues/324
