### ISSUE TITLE
clip retrieval website is not working

### ISSUE THREAD

**Issue by xiaoyudxy** [rom1504/clip-retrieval#365]
I tried to type in a keyword and then hit Search, but there was no response after a long time 。The web site is : https://rom1504.github.io/clip-retrieval/?back=https%3A%2F%2Fknn.laion.ai&index=laion5B-H-14&useMclip=false

so,why the website is not working?

![screenshot-20240228-135621](https://github.com/rom1504/clip-retrieval/assets/23376359/b76280d3-7293-4bd0-b5d9-a65f047b99d3)

**Comment by AlirezaSalehy** [comment]
Same problem. Please investigate it.

**Comment by rom1504** [comment]
https://github.com/rom1504/clip-retrieval/issues/324
