### ISSUE TITLE
Clip Retrieval UI / Clip front is down

### ISSUE THREAD

**Issue by Ahmedkoptan** [rom1504/clip-retrieval#378]
Attempting to use Clip Retrieval UI / Clip front but it seems broken : https://rom1504.github.io/clip-retrieval/?back=https%3A%2F%2Fknn.laion.ai&index=laion5B-H-14&useMclip=false

**Comment by tripplyons** [comment]
It seems like the [knn.laion.ai](https://knn.laion.ai/) endpoints no longer work. In the web frontend you mentioned, there is a CORS error, but even if I try locally running `curl 'https://knn.laion.ai/indices-list'` the server returns an error.

**Comment by rom1504** [comment]
#324
