### ISSUE TITLE
Generating prompts from an image (VQGAN)

### ISSUE THREAD

**Issue by johndpope** [rom1504/clip-retrieval#4]
I'm investigating how to generate prompts from an image
There was some instructions to encode_text + encode_image using faiss here 
https://github.com/mlfoundations/open_clip/issues/1

I was digging through github and came across this codebase.
Does this repo do that? It doesn't seem so. could it?

Basically want to throw conceptual captions + be able to introspect an image for captions.
https://github.com/google-research-datasets/conceptual-12m

**Comment by rom1504** [comment]
Hi,
This codebase doesn't do that, however these repos (which are using a similar idea) do, I advise you have a look at them:
* https://github.com/dzryk/clip-grams to generate a bunch of ngram embeddings using clip text encoder
* https://github.com/dzryk/antarctic-captions to find the right ngrams using clip embeddings and a knn index, and then combining that with an attention model to produce caption of an image

**Comment by johndpope** [comment]
Cool thanks
