### ISSUE TITLE
How to create indices.json from index file ?

### ISSUE THREAD

**Issue by Talhaz** [rom1504/clip-retrieval#42]
echo '{"example_index": "output_folder"}' > indices_paths.json 
this command is not working .

**Comment by rom1504** [comment]
What do you mean it's not working ?
This command create a file with `{"example_index": "output_folder"}` as content
You can also create the file with another editor

**Comment by Talhaz** [comment]
> What do you mean it's not working ?
> This command create a file with `{"example_index": "output_folder"}` as content
> You can also create the file with another editor


I am a beginner can u help me how to create an indices.json from index file 
let suppose I have a file  **HNSW15-efSearch=16383.index** now how to create an indices.json 
which I will use in clip back command  `clip-retrieval back --port 1234 --indices-paths indices_paths.json`

**Comment by Talhaz** [comment]
What is actually a indices_paths.json file ? Why do we need this ?

**Comment by rom1504** [comment]
create a folder like `output_folder` then move your `HNSW15-efSearch=16383.index` as `image.index` in that folder
you also need to put in that folder your metadata/ folder containing the parquet metadata (that you got from clip inference)
then indices_paths.json can contain `{"example_index": "output_folder"}` which tells clip back to use the index and metadata in `output_folder`

**Comment by rom1504** [comment]
if you use clip index, it will automatically create that `output_folder` with all the right names

**Comment by Talhaz** [comment]
I'm using a collab 
this is my indices.json file contains `{"/content/output_folder/image.index": "/content/output_folder"}
 `
 still it throws error 
 ` File "/usr/local/lib/python3.7/dist-packages/clip_retrieval/clip_back.py", line 207, in parquet_to_hdf5
    if k not in columns_to_return:
TypeError: argument of type 'int' is not iterable`

**Comment by rom1504** [comment]
yes you're missing the metadata folder. It's probably in your embeddings directory

**Comment by Talhaz** [comment]
Ok now its working 
it creates a `/content/output_folder/metadata.hdf5`

**Comment by Talhaz** [comment]
```
loading clip...
loading metadata...
loading indices...
 * Serving Flask app "clip_retrieval.clip_back" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:1234/ (Press CTRL+C to quit)
```

**Comment by rom1504** [comment]
if doing this in colab, you'll need to figure out a way to expose it to the outside
maybe you can do something like this https://github.com/rom1504/dalle-service/blob/master/dalle_back.ipynb using a thread and localtunnel
it would be easier to run it locally

**Comment by Talhaz** [comment]
Thanks

**Comment by rom1504** [comment]
I fixed a few issues and included your use case in the colab, it should do what you want now

(and btw I intend to make an end to end command to make things easier https://github.com/rom1504/clip-retrieval/issues/31 probably in a few weeks)

**Comment by Talhaz** [comment]
> I fixed a few issues and included your use case in the colab, it should do what you want now
> 
> (and btw I intend to make an end to end command to make things easier #31 probably in a few weeks)

Appreciated
