### ISSUE TITLE
Images does not rendering  on clip front 

### ISSUE THREAD

**Issue by Talhaz** [rom1504/clip-retrieval#52]
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at HTMLElement.renderImage (clip-front.js:385)
    at clip-front.js:426
    at Array.map (<anonymous>)
    at HTMLElement.render (clip-front.js:426)
    at HTMLElement.update (lit-element.js:220)
    at HTMLElement.performUpdate (updating-element.js:555)
    at HTMLElement._enqueueUpdate (updating-element.js:508)`

**Comment by Talhaz** [comment]
`Could not load content for webpack:///./src/clip-front.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)`
`Could not load content for webpack:///./src/clip-service.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME)`

**Comment by rom1504** [comment]
are you using the last version of the code ?

**Comment by Talhaz** [comment]
which is the latest versoin ?

**Comment by rom1504** [comment]
2.11.2

**Comment by rom1504** [comment]
Can you check in network tab what your backend is answering?

**Comment by Talhaz** [comment]
yes its 2.11.0

**Comment by rom1504** [comment]
2.11.0 is not the last version, you need 2.11.2
What is your backend answering in network tab ?

**Comment by Talhaz** [comment]
No same errir 
`clip-front.js:385 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at HTMLElement.renderImage (clip-front.js:385)
    at clip-front.js:426
    at Array.map (<anonymous>)
    at HTMLElement.render (clip-front.js:426)
    at HTMLElement.update (lit-element.js:220)
    at HTMLElement.performUpdate (updating-element.js:555)
    at HTMLElement._enqueueUpdate (updating-element.js:508)`

**Comment by Talhaz** [comment]
this is my backend url = "http://192.168.10.4:1234/"
index = 'E:\Noora\clip_retrieval_indexes\jumpsuit\image.index'

**Comment by Talhaz** [comment]
logs of clip_back 
`192.168.10.4 - - [24/Sep/2021 18:10:17] "POST //knn-service HTTP/1.1" 200 -`

**Comment by Talhaz** [comment]
> 2.11.0 is not the last version, you need 2.11.2
> What is your backend answering in network tab ?

"ok"
i updated to 2.11.2 but still same error

**Comment by rom1504** [comment]
What is your backend answering in the network tab of chrome when you are using the front end ? https://developer.chrome.com/docs/devtools/network/

**Comment by rom1504** [comment]
do you have a metadata folder in E:\Noora\clip_retrieval_indexes\jumpsuit\

**Comment by Talhaz** [comment]
> do you have a metadata folder in E:\Noora\clip_retrieval_indexes\jumpsuit\

Yes

**Comment by Talhaz** [comment]
> What is your backend answering in the network tab of chrome when you are using the front end ? https://developer.chrome.com/docs/devtools/network/

Nothing it only says "ok"

**Comment by Talhaz** [comment]
![Screenshot](https://user-images.githubusercontent.com/29279151/134702020-7e219d0e-314e-40a3-92c2-af654ef88d79.png)

**Comment by rom1504** [comment]
> Nothing it only says "ok"

that is not possible, can you share a screenshot of that network tab ?

**Comment by rom1504** [comment]
what did you put in indices-path.json ? it's very weird the front is display the path of the index instead of the name

**Comment by Talhaz** [comment]
> what did you put in indices-path.json ? it's very weird the front is display the path of the index instead of the name

{"E:\\Noora\\clip_retrieval_indexes\\jumpsuit\\image.index": "E:\\Noora\\clip_retrieval_indexes\\jumpsuit"}

**Comment by rom1504** [comment]
ok the first part should probably be a name like "jumpsuit" instead

**Comment by rom1504** [comment]
what about the network tab ?

**Comment by Talhaz** [comment]
> > Nothing it only says "ok"
> 
> that is not possible, can you share a screenshot of that network tab ?
![Capture](https://user-images.githubusercontent.com/29279151/134729514-e2f33e38-212d-4eee-967f-ce69ce30b427.PNG)

**Comment by rom1504** [comment]
yeah that's not what I'm asking.
I'm asking about the network tab in chrome *while you use the front end*
Check https://developer.chrome.com/docs/devtools/network/ if you don't know about the network tab

**Comment by Talhaz** [comment]
> yeah that's not what I'm asking.
> I'm asking about the network tab in chrome _while you use the front end_
> Check https://developer.chrome.com/docs/devtools/network/ if you don't know about the network tab
![Capture](https://user-images.githubusercontent.com/29279151/134731507-0b139232-828c-4e8b-98d8-272871517589.PNG)

**Comment by rom1504** [comment]
this is not the frontend.
are you running the frontend locally ? if yes you need to go to that, use it, and then check the network tab, click on that line on the right to get the answer of the backend

if you're not running the frontend locally, that's going to be an issue since your local ip is not going through https 

maybe use https://ngrok.com/ so it goes through https

**Comment by Talhaz** [comment]
im running both locally

**Comment by Talhaz** [comment]
![Captureee](https://user-images.githubusercontent.com/29279151/134740718-c858a9f8-708e-48f0-8395-d7b809049df2.PNG)
![Captureeet](https://user-images.githubusercontent.com/29279151/134740723-42aa2331-6572-4b00-8086-aaf6a3c9d0e0.PNG)

**Comment by rom1504** [comment]
Can you click on this list display in the console ? Or the same in the network tab to get the content sent by the back ?
And then share that

Oh and make sure you did update your frontend with the latest commits

**Comment by rom1504** [comment]
this seems to be fixed
