### ISSUE TITLE
Image are not rendering in the clip-retrieval front UI

### ISSUE THREAD

**Issue by yogeshv4** [rom1504/clip-retrieval#60]
The images are being fetched and KNN has been performed on the data. It can be seen on the console that the similar images are fetched as an array object. However, the images are not being displayed on the front end.
Is there any solution to this issue?

**Comment by rom1504** [comment]
can you try to uncheck the safe mode box on the left ?

**Comment by yogeshv4** [comment]
![image](https://user-images.githubusercontent.com/92301622/136774886-9dabff57-98c1-43f8-a3ab-5bcd83c94c11.png)

**Comment by rom1504** [comment]
you should be able to scroll down to see more images, doesn't that work?

**Comment by Talhaz** [comment]
> you should be able to scroll down to see more images, doesn't that work?

no it does not work

**Comment by Talhaz** [comment]
> https://github.com/rom1504/clip-retrieval/blob/main/front/src/clip-service.js#L18 Calling null just means there is no text in the query which is what is expected I see you have results displayed in the console, are you sure it didn't work ?
> 
> Are your backend and frontend up to date ?

ok

**Comment by Talhaz** [comment]
why the scroll does not work on my index

**Comment by Talhaz** [comment]
> it seems to be working, no new image is displayed?

yes

**Comment by Talhaz** [comment]
ok let me check
