### ISSUE TITLE
Text query on index built with image embeddings

### ISSUE THREAD

**Issue by wzlxjtu** [rom1504/clip-retrieval#76]
Hi @rom1504,

Thanks for the great work on this retrieval system. I have a question about your implementation details. In `README` you have this sentence: `image.index containing a brute force faiss index for images`. I'm wondering if the image index behind the retrieval ui is a brute force index (flat index)? From the code looks like you used autofaiss, then I would expect the index to a quantized one.

I have this question because I'm also using autofaiss to build an index on 100 million images using CLIP embeddings. What I observed is that on this index, image query gives decent performance. However, text queries return very poor performance. This issue disappears when I switched to use a flat index. I think the underlying reason is that image and text embeddings span into disjoint clusters in the CLIP latent space, as discussed here: https://twitter.com/metasemantic/status/1356406256802607112
Building a quantized Faiss index somehow increased the gap between image and text embeddings and making the retrieval fail on text queries. I'm wondering if you also had this issue and then decided to use a flat index to overcome this issue? If so, I would expect an index with 400M images to be bulky and slow?

Thanks for your kind reply!

**Comment by rom1504** [comment]
Hello,
good catch, `image.index containing a brute force faiss index for images` is not correct anymore. I used a flat index only for small indices at the beginning of this project. I will fix that in the readme

This tool is indeed using autofaiss and hence using approximate knn with a degree of approximation that depends on the memory constraint given to autofaiss.
You can see the difference of performance in https://rom1504.github.io/clip-retrieval/ by choosing the index on the left.

I have observed that indices built on clip text and image embeddings (400m of them) work well if using indices of size at least 16GB, and work very well for 64GB (I can give you the exact indices kind if you interested but https://colab.research.google.com/github/criteo/autofaiss/blob/master/docs/notebooks/autofaiss_index_selection_demo.ipynb should give you a good idea about this)

as you can check on https://rom1504.github.io/clip-retrieval/ all kind of queries work very well (text to text, text to image, image to text, image to image)

I have computed knn recalls for all indices, and the best recall I got are around 70% for the largest indices

Indeed using a flat index beyond a few million of points does not work. Approximate knn are needed and usually work very well

I am wondering if you used a too small index for your 100M embeddings experiment ?

I'm glad you're using autofaiss.

I'm curious about what are your plans ?

if you want to play locally with some large clip-embeddings indices, some big indices of laion400m are available there https://the-eye.eu/public/AI/cah/laion400m-indexes/

**Comment by wzlxjtu** [comment]
Thanks for such a prompt reply! I was using a 16G index and running `autofaiss score_index` shows `'1-recall@20': 0.992`. I can try to increase the index size to larger and see if that helps.

It's very helpful to know that your text queries work well on the image index. At least now I know it's possible to do. My other guess is that data in LAION-400M is cleaner. One their page (https://laion.ai/laion-400-open-dataset/) it says `we calculate the cosine similarity of both embedding vectors and drop all samples with a similarity below 0.3.`. I'm planning to try to filter my data with the same rule and see if that helps.

**Comment by rom1504** [comment]
what value of 20-recall@20 do you get? that one is much harder and that's the one I was mentioning
did you set max_index_memory_usage to 16GB and not only current_memory_available ?

laion400m is indeed filtered to have matching text and image pairs, and that makes it a good dataset to train models such as clip or dalle
for this specific retrieval use case however, the text and image matching does not matter as the indices are built on the text part or the image part independently: you could build such indices with only text or only images

**Comment by wzlxjtu** [comment]
> what value of 20-recall@20 do you get? that one is much harder and that's the one I was mentioning. Usually if you get more than 50% for 20-recall@20, you'll get pretty decent results did you set max_index_memory_usage to 16GB and not only current_memory_available ? (can you maybe share the index key that was chosen by autofaiss?)

My '20-recall@20': 0.6614999999999996.
index_key:"OPQ64_448,IVF65536_HNSW32,PQ64x8"
Yes I set `max_index_memory_usage` to be 16G and `current_memory_available` is 30G. 

> laion400m is indeed filtered to have matching text and image pairs, and that makes it a good dataset to train models such as clip or dalle for this specific retrieval use case however, the text and image matching does not matter as the indices are built on the text part or the image part independently: you could build such indices with only text or only images

Definitely makes sense!

**Comment by rom1504** [comment]
ok, that score seems pretty reasonable
you said that "However, text queries return very poor performance", how did you measure that exactly? what results do you observe and what did you expect? what kind of dataset is it?

**Comment by wzlxjtu** [comment]
I'm fixing one thing and I'll get back to you with what I got. Thank you!

**Comment by wzlxjtu** [comment]
So I trained a larger Faiss index. It's again on the 100M common crawl images. This time the index is 32GB and 20-recall@20 reaches 0.899. I'm still observing that text retrieval quality is poor.

For example, when I search `red car` in your system (https://rom1504.github.io/clip-retrieval/?back=https%3A%2F%2Fknn.laion.ai&index=laion_400m_128G&query=red+car), it returns decent red car images.

When I search the same thing in my index, it returns these images as top 3:
- https://lakisarah.files.wordpress.com/2020/12/screen-shot-2020-12-26-at-6.13.20-pm.png?w=1200
- https://nicichiarasa.files.wordpress.com/2021/01/horse-and-car.jpg?w=676
- https://static.wixstatic.com/media/eaff7f_20766f63569a4b3fb7bf7ab4f6d1d72f~mv2.jpg/v1/fit/w_1000%2Ch_744%2Cal_c%2Cq_80/file.jpg


The results seem to be dominated by images with text. My theory is that since the index recall looks ok, the problem is on the data: LAION data is cleaner since it's filtered with similarity threshold, and these kind of images are discarded.

Interestingly, if it's a flat index, the results are much more reasonable. In the case of red car, a flat index with the same set of images would return these images as top 3:
- https://janemount.files.wordpress.com/2018/07/eca8a-36853937_250754579046897_3977563955785629696_n.jpg?w=640
- https://i.pinimg.com/236x/e8/b2/bf/e8b2bf49c41a2edc4fa965d2e2cdf62c.jpg
- https://graffiti-unlimited.com/system/image_mixeds/258950/original_jpg/bombing_1604178770979.jpg?1604178855

Looks like the Faiss quantization somehow degrades the text retrieval quality by quite a bit. This is also noticed when I query with a smaller LAION index: https://rom1504.github.io/clip-retrieval/?back=https%3A%2F%2Fknn.laion.ai&index=laion_400m_16G&query=red+car

**Comment by rom1504** [comment]
interesting
can you try "a photo of a red car" on your index?

**Comment by wzlxjtu** [comment]
Yep I was already using "a photo of a red car". I also tried "red car", it didn't make it better lol.

**Comment by rom1504** [comment]
quite interesting you're getting results significantly worse than laion400m
I guess then yeah give it a try to keep only image and text that match with a 0.3 clip threshold (since you already have the clip embeddings it should be fast to do)

**Comment by rom1504** [comment]
ah one important point: is your dataset fully shuffled? we extract the training set for the index among the first files so if your dataset is not shuffled (and hence the first files are not representative of the whole set), it could have a negative impact

**Comment by rom1504** [comment]
I used https://github.com/rom1504/cah-prepro/blob/main/deduplicate/cah_stats_spark.py#L83 to shuffle

**Comment by wzlxjtu** [comment]
I believe it's shuffled but I need to double check.

I've also noticed that text query quality on LAION degrades quite a big between 128G and 64G. For example:
https://rom1504.github.io/clip-retrieval/?back=https%3A%2F%2Fknn.laion.ai&index=laion_400m_128G&query=red+car
vs.
https://rom1504.github.io/clip-retrieval/?back=https%3A%2F%2Fknn.laion.ai&index=laion_400m_64G&query=red+car

From this I think the performance is sensitive to the compression ratio as well. I'll also train an 128G index and see what happens.

**Comment by rom1504** [comment]
I'm not sure I would say it degrades much from this example alone
"a photo of a red car" gives very similar results with both indices for laion

**Comment by wzlxjtu** [comment]
Getting back to you with some new findings!
So I tried two things: 
1) Train a larger Faiss index

Last time I was using a 26G index. This time I trained a 238G index (for some reason autofaiss cannot found an index size in between 26G and 238G). This time index_key:"HNSW32", compression ratio:0.88, '20-recall@20': 0.77.
The top 5 results for "a photo of a red car":
https://2.bp.blogspot.com/-7PV9IYXKzD8/WcZ-LZbj3uI/AAAAAAAAqZo/AKSsTtrKH2weKdWpfOG_dpVHpUcanOTjACLcBGAs/s640/4.jpg
https://timdobbsphotography.files.wordpress.com/2018/07/holga_e100vs_009.jpg
https://www.sloannota.com/wp-content/uploads/2021/01/Screen-Shot-2021-01-28-at-11.31.04-AM-sm.png
https://pocketdiarybudapest.files.wordpress.com/2016/09/ce7e0-62.jpg?w=640&h=426
http://russellfreeman.com/wp-content/uploads/2011/11/russ_colombia_renault_repair-228(pp_w639_h479).jpg
As compared to the 26G index:
https://reddwarfquotes.com/wp-content/uploads/2016/12/But-kippers-vindaloo.jpg
https://www.mppsociety.com/wp-content/uploads/2016/12/derpyfrs-scion-frs-ssr-ms3-4-640x427.jpg
https://sketchingwordscom.files.wordpress.com/2020/10/fullsizeoutput_8ee.jpeg
https://lakisarah.files.wordpress.com/2020/12/screen-shot-2020-12-26-at-6.13.20-pm.png?w=1200
https://brattleboroadventurecom.files.wordpress.com/2019/02/img_3466-1.png

This seems to be an improvement. However, when I search for "a photo fo a red guitar", from 238G index I got:
https://cdn.shopify.com/s/files/1/0410/9110/4924/products/sunbrella-canvas-jockey-red-5403_90f4df10-86f9-4d43-bb38-6f101636e87e_1024x1024.jpg?v=1616687617
https://couleursjapon.com/1807-home_default/tissu-chirimen-rouge-uni.jpg
https://www.eqsuk.com/images/products/838_1_590x504.jpg
From 26G index I got:
http://2.bp.blogspot.com/-1Dxh3M8bOuQ/VSs9IKaxWXI/AAAAAAAAFqI/G_vbHh0ULgw/s1600/footprint%2Bguitar.jpg
https://guitartwitt.com/wp-content/uploads/2021/06/20210619_200541_0000.jpg
https://www.divideandconquermusic.com/uploads/1/3/4/0/13408633/7233565.jpg?263
This time the larger index totally fails.

2) Clean the common crawl data by throwing away image-text pairs with a cosine similarity below 0.3.
After cleaning, only 26% data remains.

This time when I search for red guitar, 238G index gives:
http://i612.photobucket.com/albums/tt210/gratyngen/048-1.jpg~original
https://cdn.shopify.com/s/files/1/0550/4437/4714/products/fecd4zgjvy4je5n833kh_a61a7d8d-86d9-4228-9479-1136885b9654.jpg?v=1619827290
https://sirclocdn.com/nafiriguitar/products/_200924153910_Epi_full.jpg

which looks much more reasonable.
26G index gives:
http://i612.photobucket.com/albums/tt210/gratyngen/048-1.jpg~original
https://cdn.shopify.com/s/files/1/0550/4437/4714/products/fecd4zgjvy4je5n833kh_a61a7d8d-86d9-4228-9479-1136885b9654.jpg?v=1619827290
https://bunkerguitars.com/wp-content/uploads/2019/12/nikon-photos-192.jpg

Looks like cleaning the data greatly helps.

**Comment by rom1504** [comment]
Very interesting!
What I think this show is that clip is bad for some examples, so if you have enough such bad examples in the dataset, the index will return a lot of them in first results

regarding the index size, something I note is your hnsw recall is actually lower than the recall you had with your 32GB ivf. The size is not the only thing that makes the index quality vary

is it a good solution for you to pre-filter the dataset with clip matching?

**Comment by wzlxjtu** [comment]
Yeah, it's very interesting to see that Faiss quantization actually brings these bad examples to the front.

Pre-filter with CLIP is definitely helping for common crawl images specifically, but not for cases when images are not captioned. I think in these cases we need to find other methods to score the image quality.

**Comment by rvencu** [comment]
We will also have a large list of non or poorly captioned images and will have to look into this to process them

Obțineți Outlook pentru iOS<https://aka.ms/o0ukef>
________________________________
De la: Zelun Wang ***@***.***>
Trimis: Thursday, December 2, 2021 1:49:02 AM
Către: rom1504/clip-retrieval ***@***.***>
Cc: Subscribed ***@***.***>
Subiect: Re: [rom1504/clip-retrieval] Text query on index built with image embeddings (Issue #76)


Yeah, it's very interesting to see that Faiss quantization actually brings these bad examples to the front.

Pre-filter with CLIP is definitely helping for common crawl images specifically, but not for cases when images are not captioned. I think in these cases we need to find other methods to score the image quality.
