### ISSUE TITLE
Using clip retrieval on our own model

### ISSUE THREAD

**Issue by uahsan3** [rom1504/clip-retrieval#94]
Is it possible to generate the embeddings using our own trained model? Thanks!

**Comment by rom1504** [comment]
Maybe yeah, there would need to be some changes in clip inference
What model is it ?

**Comment by uahsan3** [comment]
It's trained on a custom dataset using ResNet 50 and ResNet101 as vision
backbone. So not zero shot embeddings anymore but embeddings from a trained
model.

**Comment by rom1504** [comment]
So what are you trying to do in relation with clip retrieval exactly? Image search?

**Comment by uahsan3** [comment]
Yeah I need a scalable system to quickly compute embeddings on my dataset
and retrieve images via text queries as well as retrieval via image search.
So this repo is an exact fit.

**Comment by rom1504** [comment]
I understand you train these models for classification, is that right?
That means you can maybe use them for image search
You cannot use them for text search as the clip text encoder is not aligned with your image models

You could adapt the clip inference script to compute embeddings with your model. And then use autofaiss to build the indices as is done in clip index
